### ISSUE TITLE
「橷」的取碼

### ISSUE THREAD

**Issue by SyaoranHinata** [Jackchows/Cangjie5#1]
「橷」字原取「木中一山」，現在表主刪除了，改成「木中心弓」。
竊以爲兩種取碼，是基於不同的字形。建議同時保留兩者。

「木中一山」者，右下爲「儿」，視作跟上方連體，如圖所示：
http://ii.911cha.com/zidian/kai/28/6a77.gif

「木中心弓」者，右下爲「几」，視作跟上方分體，如圖所示：
http://www.handedict.de/jt/zi/images/hanzi/kai/small/%E6%A9%B7_kai.png

兩個字形被編在相同的Unicode碼位內，使用不同字型時會有不同顯示。故建議同時保留兩者。

**Comment by Jackchows** [comment]
多謝指正。
刪除「木中一山」是我理解錯了，我將第三碼的「一」理解成右上方「匕」的一橫，因為認為此碼是錯了。
認同應當保留兩個字型，但是兩個取碼分別應該是「木.中一山」（右下為「儿」，連體）和「木.中心.弓」（右下爲「几」，分體）。
至於右上的「匕」作「一」還是作「丿」，我認為不構成取碼差異，都應取整體「心」。

**Comment by SyaoranHinata** [comment]
明白。竊以爲第三碼的「一」是「北的左旁」的第二筆。

因爲整個「兠」是連體字，所以只能由左上開始取頭三碼「中一一」及尾碼「山」。

**Comment by SyaoranHinata** [comment]
剛才我再論及「兠」字，似乎「儿」底者仍有兩種取碼方式：LMMU與LPHU之爭，此字的「儿」底者也可能有DLMU與DLPU兩種取碼，詳見 [https://github.com/Jackchows/Cangjie5/issues/17#issuecomment-365384307](https://github.com/Jackchows/Cangjie5/issues/17#issuecomment-365384307)

**Comment by SyaoranHinata** [comment]
剛剛一査「橷」字，採用「⿰木兠」這寫法的話，《漢文庫典》取「木中心山」：
http://chidic.eduhk.hk/v.php?id=7612
換言之是把「兠」的上方視爲次字首，拆作「木.中心.山」了。

似乎除了九九年五代的「木中一山」外，也宜添上〇三年五代的「木中心山」（目前沒有後者）。
