### ISSUE TITLE
「舌」兼容「竹十口／一十口」

### ISSUE THREAD

**Issue by danny0838** [Jackchows/Cangjie5#100]
Unicode 兩者都有收：

![default](https://user-images.githubusercontent.com/531417/42489703-1d93d09e-843f-11e8-8274-cb70e1a5ed80.png)

目前很多衍生字已有兩種編碼，但「舌」只有「竹十口」，「舍」只有「人一十口」，其它還有些有漏就不一一列舉。

**Comment by SyaoranHinata** [comment]
「舍」其實不從「舌」，上方像屋頂和樑柱，像「余」的頂部，其第三筆不會寫成撇。所以不宜設「人竹十口」之碼。

**Comment by SyaoranHinata** [comment]
其他的字，本可按字理區分：

「舌」，口中辨味器官，首筆爲橫。字義與「舌」有關者，如「舐、舓、舔、舑、舕、舚、舏、𦧺、舙、甜」；或讀若「舌」、「甜」或「韱」者，如《廣韻》薛韻、添韻、鹽韻（擧平以賅上去），粵音it韻、im韻者，即「恬、栝、𦧡」或「絬、銛」等字從此。

「⿱千口」，首筆爲扁撇。從「⿱千口」得聲者，如《廣韻》末韻、黠韻、夬韻，粵音aat韻、ut韻、aa韻者從此，如「括、刮、颳、活、闊、話、蛞、䒷、桰、銽、适、鴰」等字。

竊以爲，倉頡取碼可設兼容，但若有重碼時，宜以正形爲主。注意「栝、銛」二字，本有從「⿱千口」者與從「舌」者，音義不相同，奈何Unicode自打嘴巴地合併編碼。

至於「乱、辞」則爲「亂、辭」之訛寫；「敌」則爲「敵」之訛寫。訛寫字向來習慣作撇，不必收橫起筆者。

**Comment by danny0838** [comment]
無論字源如何，Unicode 「舍」字的 V 源就是呈「人竹十口」形，我認為應該設兼容。

**Comment by danny0838** [comment]
查了些資料，調整一下原則：
1. 「舌」（shé，口中辨味器官）正字作「⿱干口」，俗作「⿱千口」，從「舌」者皆設兼容碼，如：甜恬舔舐䣶咶𫇔𮍴𦧜𫫞𫇖𦧗𦧰𦧐𪌩𦧎𪎾𦧬𧱳。
2. 「𠯑」（guā）作「⿱千口」，從「𠯑」者不設兼容碼，如：活㓉括秳䄆刮䀨話䟯䯏聒佸姡蛞𨈸𦧘𦧠𩈙鴰䒷筈髺适颳趏𡯢𣭪𦧍𤫵䦚。
3. 從「舍」者取「人一十口」，兼容個別 Unicode 有收的異體字，如「舍」有「人竹十口」、「捨」有「人土口」。
4. 簡化字、俗寫字習皆作「⿱千口」，不設兼容碼，如：乱敌辞㔚。
5. 其他或難查證者，僅兼容 Unicode 所收字形，如：𬛥𬵏𭁦𭓯𭥹𮍻𮝐。

歷史上因「舌」「𠯑」形近混用的字，如 @SyaoranHinata 兄所提的「栝、銛」，因至少一種用法與「舌」有關，故比照「舌」設兼容碼以便利使用者。

一些方言字、韓字、喃字等，比如：𦧜𫫞𫇖，因為是以「舌」為形符的形聲字，字義也和「舌」有關，因此即使該地的用字標準是「⿱千口」，也一律比照「舌」設兼容碼以便利使用者。

**Comment by SyaoranHinata** [comment]
沒想到越南字形竟然提交了第三筆從撇的「舍」，
這種字形，《[異體字字典](https://dict.variants.moe.edu.tw/variants/rbt/word_attribute.rbt?educode=A03403)》不收，[歷代碑帖拓本](http://coe21.zinbun.kyoto-u.ac.jp/djvuchar?query=%E8%88%8D)都不見，
卻因這樣而混進來了，
喃字至今還是個比較混亂的坑，但他們能好好整理的人手也不多。
只好寄望、祝福有志於喃字硏究的越南朋友早日復興喃字。
