### ISSUE TITLE
吞／呑

### ISSUE THREAD

**Issue by danny0838** [Jackchows/Cangjie5#101]
Unicode 把「吞」（一大口）和「呑」（竹大口）分開編碼，但衍生字很多是兩種字形混合編碼，例如「㖔」只有「口一大口」但 Unicode 兩種字形都有收：

![default](https://user-images.githubusercontent.com/531417/42490000-b3174ca8-8440-11e8-98ed-ca0a3ebead1d.png)

這些字應該要兼容兩種取碼。

有個要注意的是「喬」上半部按字源與「呑」無關，且此字及其衍生字無論是官方或 Unicode 都沒有收「吞」的字形，因此不須設兼容。

另一個問題是，按字源「吞」是正字，但早期倉頡似乎只收「呑」，而 Big5 未收「呑」，導致市面上許多倉頡輸入法有設兼容碼「竹大口＝吞」，即使後來有了 Unicode，目前微軟倉頡及許多倉頡輸入「竹大口」的第一候選字仍是「吞」，其次才是「呑」，很多使用者也已經建立了「吞＝竹大口」的輸入習慣。

要嚴格按字形取碼，或是按既往習慣加上「竹大口＝吞」的兼容碼？若要加兼容碼，候選順位怎麼設定？可能要大家討論下怎麼處理。

**Comment by mrhso** [comment]
「吞」取「竹大口」和仓颉官方将码表强行五大码化有关。因为当时仓颉系统主要用「呑」，而在仓颉系统中的五大码输出对应到了「吞」。

**Comment by Jackchows** [comment]
會做「竹大口/一大口」兼容。不同意加「吞（竹大口）」。
