### ISSUE TITLE
「兓」兼容「一山一女山／大山大女山」

### ISSUE THREAD

**Issue by danny0838** [Jackchows/Cangjie5#102]
如題，官方和 Unicode 兩種字形（一山一女山／大山大女山）都有收，應該要做兼容處理。

![default](https://user-images.githubusercontent.com/531417/42490324-2fcb232c-8442-11e8-824f-762dad786430.png)

可能要討論的是要不要加上 J源和 K源的字形兼容碼？怎麼取碼？

**Comment by SyaoranHinata** [comment]
同意兼容，不過後者會否取「手山.手竹山」或「手山.手女山」爲佳？

按：《漢文庫典》中，「㐄」取「手女」（キ𠃋），「兂」取「大女山」（𠂇𠃋乚），拆法並不統一。
而「㐄」本身是輔根，「兂」貌似取「手竹山」（キ㇒乚）更合理。

**Comment by SyaoranHinata** [comment]
1. 「本項目的修訂原則」是指有官方編碼而不是明顯錯誤（像「斉」字般）就沿用，即使於取碼規則上有爭議都照用，對嗎？
2. 若不理會(1.)，以規則來論，「兂」應取「手竹山」，對嗎？

**Comment by Jackchows** [comment]
1. 是。
2. 我覺得可以取「手山」。

**Comment by SyaoranHinata** [comment]
2. 嗯，「手山」也想過，只是怕別人會否覺得輔根「㐄」的豎能否變作撇而已。若可，則同意「手山」。
