### ISSUE TITLE
「𧮣」

### ISSUE THREAD

**Issue by danny0838** [Jackchows/Cangjie5#103]
「𧮣」目前編碼「月金.卜口.口」，但按倉頡規則，應編碼作「月金.卜卜.口」？（字首「貝貝」，次字首「亠亠」，其餘次字身）

**Comment by Jackchows** [comment]
「誩」切割成「言、言」比切割成「⿰亠亠、⿰⿱二口⿱二口」更符合字形特徵。

**Comment by danny0838** [comment]
五代「春」、「秦」、「冬」、「薛」、「登」等字也是視為特殊字首取碼而有爭議，目前本項目有設兼容。「言」相關字是否也要比照設兼容？

**Comment by Jackchows** [comment]
「言」不是複合字首。「譶」取「卜口卜口口」是因為倉頡六代對三疊字取碼作了規定，將重複的部件整體視為一塊。漢文庫典受六代影響也遺留了這種取法。但本項目沒有跟從這種取法。
對於「誩」字，橫切和豎切都是一刀切，碼長也一樣，這時候就需要考慮字形特徵。
![qq 20180712141615](https://user-images.githubusercontent.com/10194519/42615753-297f8cc2-85de-11e8-9e0e-5c4e6adc595c.png)
五代手冊明確提到要考慮字形特徵（「完整原則」，76頁），這裡雖然是說輔助字形的選用，但我認為亦適用於漢字分割。

**Comment by danny0838** [comment]
瞭解，那麼「𧮣」就維持原先取碼。

三代補完計畫有兼容疊字取碼，微軟倉頡和市面上許多倉頡也有支援，我們要也支援嗎？

**Comment by Jackchows** [comment]
暫不支援。

**Comment by danny0838** [comment]
ok，瞭解。
