### ISSUE TITLE
「汞」視為連體或分體字？

### ISSUE THREAD

**Issue by danny0838** [Jackchows/Cangjie5#104]
「𧋔」目前編作「一水.中一戈」，但是否應拆成「一.水.中戈」？

**Comment by Jackchows** [comment]
![default](https://user-images.githubusercontent.com/10194519/42609092-6e9b247c-85bd-11e8-82c2-5e0864cd833b.png)
五代手冊的字形是連體字。不過含「汞」的字不多，可以容錯一下。

**Comment by danny0838** [comment]
字典上「汞」是7劃而非6劃，可見「工」和「水」的豎筆是分開寫而非同一筆劃。而 Unicode 所收字形有把「工」、「水」連在一起，也有分開的，倉頡也沒有中豎須視為上連與否的特別規定。因此，雖然官方把「汞」視為連體，我認為容體連體及分體取法會比較好。

![default](https://user-images.githubusercontent.com/531417/42612680-3e22a7b8-85cf-11e8-909d-8d22cadd890b.png)

**Comment by mrhso** [comment]
异议。参照「泉」等字，我认为官方的想法是分体。

**Comment by danny0838** [comment]
的確官方有好些字雖然看起來像連體，實際取碼卻不是視為連體，因此光看字形不太可靠。

**Comment by SyaoranHinata** [comment]
如果「官方的想法是分体」是眞的，那麼樓主擧的「𧋔」就應拆爲「一.水.中戈」。
同意最好兼容一下，反正含它的字不多。

**Comment by Jackchows** [comment]
想了想確實沒有甚麼證據顯示「汞」是連體字，所以還是依UCS字形按分體取吧。
