### ISSUE TITLE
修正「𣹭」「𣹳」「𣻤」

### ISSUE THREAD

**Issue by danny0838** [Jackchows/Cangjie5#106]
「𣹭」「𣹳」「𣻤」三字中的「巟」在 Unicode Code Charts 可各自取「女」或「山」（末筆作「𠄌」時視作「乚」的自然變形取「山」），但目前只有編上「女」的取碼。

此外「𣻤」最右部還有從「木」與從「水」之別，因此也須設兼容。

總體而言應該要有以下編碼：

    eyud	𣻤
    eyue	𣹭
    eyue	𣹳
    eyue	𣻤
    eyvd	𣻤
    eyve	𣹭
    eyve	𣹳
    eyve	𣻤

**Comment by Jackchows** [comment]
![23e73](https://user-images.githubusercontent.com/10194519/42608791-0270a156-85bc-11e8-8e30-a485988c5545.png)
![23ee4](https://user-images.githubusercontent.com/10194519/42608796-076295c0-85bc-11e8-9029-8ebe46b03385.png)
諮詢過IRG（表意文字小組）成員，認為U+23EE4的T源有錯，所以不取此字形。

**Comment by danny0838** [comment]
所以目前預計編入以下編碼囉？

    eyud	𣻤
    eyue	𣹭
    eyue	𣹳
    eyvd	𣻤
    eyve	𣹭
    eyve	𣹳

**Comment by Jackchows** [comment]
是。
