### ISSUE TITLE
「致／𦤶」系列字兼容（一土人大／一土竹水）

### ISSUE THREAD

**Issue by danny0838** [Jackchows/Cangjie5#108]
如題，Unicode 兩種字形都有收。

𦤶（U+26936）也是有收「一土人大／一土竹水」兩種字形（我看不出和「致」（U+81F4）有何差異），但目前只有編「一土人大」，應該也要加入「一土竹水」。

**Comment by Jackchows** [comment]
問了一下，「致」（U+81F4）从「攵」，𦤶（U+26936）从「夊」。本來應該unify的，但由於有IRG成員地區要求分開，所以就糊了。
我的想法是都兼容一下。
