### ISSUE TITLE
「育」「充」「㐬」等字是否要兼容「卜戈／大戈」？

### ISSUE THREAD

**Issue by danny0838** [Jackchows/Cangjie5#111]
官方的「育」只取「卜戈月」不取「大戈月」：

![default](https://user-images.githubusercontent.com/531417/42705037-984af9d0-8704-11e8-8ea0-a15076200440.png)

但官方的圖看起來不大像「卜」的輔助字型。

我們要跟從官方的圖把兩種「育」頭都視為可以取「卜」，或是兼容「卜戈／大戈」兩種取法？

**Comment by mrhso** [comment]
根据沈红莲女士的说法，六代和 03 五代的「卜」存在这个辅助字形：
![image](https://user-images.githubusercontent.com/13294467/42718666-8027e85c-873d-11e8-9fe4-c752e93f4280.png)
但是这个辅助字形要不要类推至其余代稍微有些争议，官方的说法有些模糊。

**Comment by SyaoranHinata** [comment]
我以爲，既然官方是兩種寫法也用「卜戈」，那麼「𠫓」直接定作「卜戈」就好，不用增加「大戈」。

說不好的話，若要很正式地宣告「斜七」這形塊，「东」之類的字要不要改碼又會引起爭議。

對了，獨用的「𠫓」字目前只有「大戈」這個碼，應加入「卜戈」。

**Comment by danny0838** [comment]
是否把「卜戈」視為支援「𠫓」字形還有一個考量點是，當 Unicode 收「𠫓」字形的字，而編碼作「卜＊」時，是否視為此字形 Unicode 有收錄？

例如 Unicode 有這個字形：
![default](https://user-images.githubusercontent.com/531417/42722971-a9ae8ace-8787-11e8-9d21-b9a391fe348e.png)

而我們有為「𣹳」設「eyve」編碼，這編碼是否應標上 [u]？

如果我們不打算支援「ekve」編碼，似乎是應視為有支援而不標記 [u]，才是比較一致的。

**Comment by SyaoranHinata** [comment]
個人覺得不用，「𠫓」無論怎麼寫，直接就視爲「卜戈」即可。

**Comment by Jackchows** [comment]
目前我是這樣處理：
若 Unicode 文檔有「卜戈」字形，則衹取「卜戈」。
若 Unicode 文檔沒有「卜戈」字形，衹有「大戈」字形，則兼容「大戈」和「卜戈」。

**Comment by danny0838** [comment]
既然我們暫時不打算接受2003版五代（马=尸一），加上已有不少倉頡支援「大戈」，使用者也常不明有疑惑，我想統一做兼容是比較合適些。

這樣很多「育」「充」「㐬」系列字都要跟著做兼容就是。

**Comment by Jackchows** [comment]
其實看作本項目不支持「![u 20ad3_t](https://user-images.githubusercontent.com/10194519/42725045-edc5bc82-87af-11e8-8356-89d605ef604f.png)」這種字形就好了，衹有 Unicode 文檔僅有「![u 20ad3_t](https://user-images.githubusercontent.com/10194519/42725045-edc5bc82-87af-11e8-8356-89d605ef604f.png)」字形的字，本項目才兼容「大戈」，其他都是「卜戈」。

**Comment by danny0838** [comment]
我反對。

Unicode 只收「大戈」時支援「大戈」和「卜戈」，Unicode 收「大戈」和「卜戈」時只支援「卜戈」。Unicode 收的字形更多，我們支援的字形更少，這怎麼樣都說不過去吧？

要嘛是統一不收「大戈」，要嘛是 Unicode 收「大戈」和「卜戈」時支援「大戈」和「卜戈」。

**Comment by Jackchows** [comment]
或者可以這樣理解：
無論 Unicode 有沒有收「卜戈」，本項目都收「卜戈」。Unicode 衹收了「大戈」的時候，本項目才收「大戈」。

**Comment by Jackchows** [comment]
增加少量「大戈」衹是為了方便，「大戈」是容錯碼，沒有必要全收。

**Comment by Jackchows** [comment]
也是為了盡量避免「Unicode 收的字形，這裡一個都沒有」這種情況。Unicode 六個來源的字形，不可能全部都收。

**Comment by danny0838** [comment]
其他字有按照這個邏輯嗎？

比如「𪱗」，Unicode 只收「金日人一弓」字形，按你這裡說的邏輯應該要收「金日人戈弓」並兼容「金日人一弓」。但你沒有這樣做，這就是不一致。

要避免不一致，就是改為我說的邏輯，或是比照「今」的做法一律不收「大戈」編碼。

**Comment by Jackchows** [comment]
真的有必要「一致」嗎？「卜戈」是標準字形，「大戈」是容錯字形，衹需要保證標準字形完整支援就可以了。
經過檢查、確定完整兼容的字形會列在 change_summary.md，其他的都是不完整兼容。

**Comment by danny0838** [comment]
為什麼要避免不一致？因為沒有人會讀心術，如果文檔沒有特別說明，看到不一致的地方就會覺得可能是有某處理錯了。像我一開始看到「育」只有「卜戈月」沒有「大戈月」，就會認為此專案是把「𠫓」比照「今」「倉」等字一樣不設兼容，然後就會認為目前的編碼和標記有很多錯誤。

如果「衹需要保證標準字形完整支援」，那最簡單的作法其實是比照「今」「倉」等字，根本不要設「大戈」的容錯碼，Unicode code charts 看到「卜戈」或「大戈」形的「𠫓」也都直接視為有支援而不標 [u]。再不然就是體現容錯碼的意義：讓看到非標準字形的使用者根據該字形取碼時能正確輸出，那就是凡 Unicode有收「大戈」形的「𠫓」都支援「大戈」。

你現在這樣的原則，既不是比照「今」「倉」，不是最簡單的作法，也不是最便利使用者的作法，不知道是在考量什麼？如果真要不一致，也不是不行，但最好就在文檔裡寫清楚，免得協作者搞不清楚本項目的原則。

**Comment by Jackchows** [comment]
收「大戈」是為了反映出該字 Unicode 沒有收「卜戈」的宇形。

**Comment by danny0838** [comment]
你沒有明白我的意思：為什麼「𪱗」不收「金日人一弓」以反映該字 Unicode 沒有收「金日人戈弓」的字形？而「𠫓」系列字就需要？

内在不一致，就表示有問題：

是「𪱗」也打算這麼做但還沒做？還是「𠫓」系列字沒有和之前的原則一致？或是這兩個例子本來就基於其他理由而不打算一致？如果是，那是基於什麼理由？

**Comment by Jackchows** [comment]
因為官方明確沒有兼容「今（人一弓）」這種字形，但有沒有兼容「𠫓（大戈）」就不太確定。

**Comment by danny0838** [comment]
我想應該就是按照 @mrhso 說的藉由2003年的新輔助字形作兼容。如果我們跟從2003的規則，那就是兼容；如果不跟從，基本上就是不兼容。

由於我們已經不跟從官方對「马」字輔助字形的修改，且跟從此規則可能衍生「东」「车」等字是否該改碼的問題，我個人是傾向不跟從。

**Comment by Arthurmcarthur** [comment]
「丿一」這個根的確存在，但是它不能用於「台標育」，因為這將破壞交叉特徵。同樣的，「丰」也不能取「土十」。
本項目已經引入了一些2003版五代的根，在與官方的交流中可以得知，基本上，只要不影響常用字的取碼，並能增強字形兼容的根，又或者是异形根都可以引入。因此「円」、「冎」的上部都是能夠引入的，同理，「育頭去點」理論上也是能引入的。
但是由於這個根存在爭議，因此引入與否的最終決定權只取決於jackchows。

**Comment by danny0838** [comment]
我覺得官方是想把「台標𠫓」劃為「卜戈＊」，2003年新增輔根的說法大概也是由於 @Arthurmcarthur 說的理由會導致「台標𠫓」應拆成「大戈」而非「卜戈」的爭議；只是官方沒想到引入這輔根可能衍生出更多問題。

這些規則大抵是為目的服務的。如果目的是確定的，我覺得就按此目的把「台標𠫓」、「𠫓」都編碼作「卜戈＊」（Unicode Code Charts 的「𠫓（大戈）」也視為已支援而不標 [u]）。至於解釋就大家再想想，我覺得可以考慮比照「改」左部視為「己」變形而取「尸山」、「今」頭視為「亽」變形而一律取「人戈」，主張「台標𠫓」視為「𠫓」的變形而一律取「卜戈」。

**Comment by Jackchows** [comment]
官方沒有說清楚「卜」到底有沒有加輔助字形。
對於 Unicode 收了「卜戈」字形的字，取「卜戈」沒有問題。
對於 Unicode 衹收「大戈」字形的字，同時收「卜戈」和「大戈」，實際上是對加根和不加輔助字形兩種情況進行容錯，可以避免明確聲明是否採納「卜」新增輔助字形。

**Comment by Arthurmcarthur** [comment]
不必強行解釋，「今」字本來就要分成「人一弓」和「人戈弓」，但是官方由於重碼過多就一直不收「人一弓」。
03五代不收「人一弓」的另外一个原因是，六代加了「亽亼」根使得「今」字在六代中一律取「人弓」，无法分辨是「亽」头还是「亼」头，因此03五代若取兩者不僅會導致五代重碼很多，還会導致六代含「今」的字產生很多重碼。同樣的，六代的規則使「感」字無法區分是台標還是陸標，因此03五代為配合六代也只取一者。
總之，倉頡在出生時便有內碼的目標，因此為此作出了很多妥協。

**Comment by danny0838** [comment]
@Arthurmcarthur 你這樣說不通，因為官方的圖明確把你所謂應該拆作「人一弓」的字形拆作「人戈弓」。

![default](https://user-images.githubusercontent.com/531417/42731141-a5071d26-8839-11e8-8e0c-818a52a1e277.png)

所以應該解釋成官方主張「今」兩種字形都取作「人戈弓」。

這和「感」不一樣，官方完全沒有為「台標感」（戈竹一口心）編碼。所以我們可以視為官方漏收而自行增加「戈竹一口心」（至於要不要加就是另一回事）

**Comment by Arthurmcarthur** [comment]
為了配合六代，「人戈弓」和「人一弓」只能取一，因為「人一弓」重碼比較多，才只取「人戈弓」啊！
不然「養」取「廿金一日女」又怎麼說？？？就是因為六代仍可以區分這「廿金一日女」和「廿金戈日女」，所以五代才一起都收啊！
六代的「感」一律取「戈的一心」，所以六代無法區分這兩者啊！

**Comment by mrhso** [comment]
……我就直说了，官方对「𠫓」加根问题的讨论在《主观人士仓颉探案集》已经收录，而从中可以看出官方也意识到了这个根会带来一些问题。
官方一开始对这个根是「举一反三，加一个辅助字形」。但是后来又说台标「反过来取『大戈』才是」，这已经很模糊了。
那么这就表示官方已经意识到其带来的问题。但这个根已经加了，不是说撤销就能撤销得了的。
所以对于官方仓颉来说，是有这个根的，因为内码难以变动。但是对于我们的项目来说，加根与否完全是我们所决定。
其实我是想加入这个根的，如果能把限定条件搞明白的话。
我说完了。

**Comment by danny0838** [comment]
把資料加密了，要別人怎麼看？不想給人看，那不如不要提。

而且我不明白加密的意圖何在。如果不想被盜，把授權聲明寫清楚就好；如果要說聲明了還是有人會偷，那就做好打官司的準備。

GitHub的公開庫一般就是默認讓大家自由或有條件自由fork的，如果不想被複製，一開始就別放上去。想要網路備份，還有很多私有庫的服務可以用。

**Comment by mrhso** [comment]
但那些文件到底还是没有加密啊。说是加密又不算加密。

**Comment by Jackchows** [comment]
我也直說了。
在現階段，我不想爭論「『卜』有沒有加輔助字形」這個問題，現在的做法是糢糊處理。
至於「不一致」，[Readme](https://github.com/Jackchows/Cangjie5/blob/master/README.md) 的開頭就說了這個項目不追求客觀。能說清楚會在 [change_summary.md](https://github.com/Jackchows/Cangjie5/blob/master/change_summary.md) 裡面說，引用的官方觀點會用明文。說不清楚的就沒有說。
各位能接受就用，不能接受就 fork 了自己改。
就這樣。

**Comment by danny0838** [comment]
好罷，「𠫓」的問題你說了算。

但還請明示一下「今」「倉」等字形的處理方針：
當 Unicode 收「亼」而未收「亽」時，我們是只取「人戈」，或是加兼容「人一」？
當 Unicode 收「亼」而我們取「人戈」的字是否要標上 [u]？

這裡就不再要求和「𠫓」一致。但我現在還是不明白「𪱗」之類的情況要怎麼處理，還請說明一下。

**Comment by danny0838** [comment]
@mrhso 不是用明文，又沒明說解密方法，就是加密。就別打模糊仗了。

**Comment by Jackchows** [comment]
衹收「人戈」，標[u]。

**Comment by danny0838** [comment]
按此，「𪱗」未來應該要標上 [u]，我沒理解錯吧？

**Comment by Jackchows** [comment]
本來這些標記就是隨手標一標方便我自己，沒打算很嚴謹。
按我最初的做法，當：
①某個部件官方收了不止一個字形
②某個字包含這個部件，但是 Unicode 文檔沒有收齊全部字形
此時，Unicode 文檔沒有收的字形會標 [u]。
所以這個字不會標 [u]。

按現在的定義，這個字應該標 [u]。

**Comment by danny0838** [comment]
確認一下，所謂「現在的定義」，是指「凡拆碼根據的字形未在 Unicode Code Charts 列出，就標上 [u]」，是嗎？

**Comment by Jackchows** [comment]
是。

**Comment by SyaoranHinata** [comment]
對於中段的爭議，我個人並沒有甚麼想說。也沒甚麼立場取向。

不過有一點不怎麼涉及上方爭辯重點的，就是無論大家抱着甚麼觀點和立場，客觀事實還是應當尊重，不容抵賴的。

比如說，那個《主觀人士倉頡探案集》的資料，當中的「第三彈.md」、「短篇/其之一.md」、「短篇/其之二.md」確確實實是加密了，正常情況打開來，全都是亂了碼，變成一般人無法閱讀的文字。連文件的第一行都寫着「本期將會加密處理」，自己都用「加密」一詞。這又豈可以卑鄙抵賴，狡稱甚麼「到底还是没有加密啊」、「说是加密又不算加密」呢？

另外，如果是理性討論的話，大家所提出的論據、論證，都應當是不同的人皆可以有平等權利去閱讀的。用這種加密東西作爲論據或論證，根本是摧毀了理性討論中每個論者都應該有的公平資訊權利。

還有一點，印象中我以往也說過。要理性討論一件事，可以大膽假設但必須說明那些假設，可以有主觀相信但必須說明主觀之處，供其他人再思考或驗證，而不是直接把假說描述成事實，或者把主觀當成是客觀。若果那些說話，連假說或申明主觀陳述都不是，是一些對人的嘲諷或攻擊，那麼對理性討論來說更是一種破壞。但願大家對倉頡的討論，不管有甚麼立場，都不要陷於不理性的泥濘中，能保持理性、對事。

**Comment by mrhso** [comment]
![image](https://user-images.githubusercontent.com/13294467/42759315-263bfb64-8939-11e8-9b1b-6585b5a0872a.png)
解决乱码（Mojibake）的方式当然是换编码了。

**Comment by danny0838** [comment]
有些人就不是要來討論的，我想直接無視就好了
