### ISSUE TITLE
产的两种繁体写法, 取码标准不一致?

### ISSUE THREAD

**Issue by dupontjoy** [Jackchows/Cangjie5#118]
産: YHHQM, 上下结构
產: YKMHM, 连体结构

**Comment by mrhso** [comment]
![image](https://user-images.githubusercontent.com/13294467/44780407-75959380-abb4-11e8-9c65-27be2f6ce097.png)
这个，是字首。
![image](https://user-images.githubusercontent.com/13294467/44780435-834b1900-abb4-11e8-8e75-1ef3e2bf60a3.png)
这个，不是。
¿RTFM？

**Comment by dupontjoy** [comment]
@mrhso 就是疑惑下面那个为什么不是字首

**Comment by Jackchows** [comment]
下面那個字首是「文」。大概官方認為「产」是連體，像「立」一樣。

**Comment by dupontjoy** [comment]
多谢回复, 好像也说得过去, 我再理理
