### ISSUE TITLE
邀請共同寫信和工作室討論這些編碼

### ISSUE THREAD

**Issue by fonthk** [Jackchows/Cangjie5#128]
大家好，我是維基教科書「倉頡輸入法」條目的其中一位編輯。

倉頡輸入法目前仍有些規則和編碼似乎彼此矛盾、難以解釋，過去有些同道寫信向官方提問，官方也回答了，但多半過於簡略、粗糙，且自相矛盾，令許多同道覺得不可從，引致爭議，而原先的爭議問題亦未解決，讓倉頡在教學、推廣上有不少麻煩。

目前計劃由社群關注相關議題的同道聯名寫信，一來令官方更為重視，二來可集眾人之力把問題的前因後果交待清楚，令官方做最有效的釋疑。

首先我打算先去信詢問影響最大的問題－－五代倉頡「春」、「冬」、「登」、「帝」系字的出格取碼。若聯名信成效良好，未來將考慮循相同模式處理其他重大爭議問題。

計劃頁面如下，歡迎有興趣的同道參與，或提出建議：
[https://zh.m.wikibooks.org/w/index.php?title=Talk:倉頡輸入法/mails](https://zh.m.wikibooks.org/w/index.php?title=Talk:倉頡輸入法/mails)

**Comment by ceku012** [comment]
目前還有另一批問題在討論，也歡迎參與及提供意見：
https://zh.wikibooks.org/wiki/Talk:倉頡輸入法/mails/2

其中問題6，按沈紅蓮的說法，「倉」應該理解為字首「𠆢」、字身「丶日丿口」。按此罕用字「𥅍」似乎應取碼「人.戈戈.山」而非「人.戈.弓山」。「𡦈、𢂂、𥅍、𨗜、𪚙、𫩧、𬡌」等字也都一樣需要改碼。這樣看起來和「永」「良」等字的處理方式較為統一。大家認為這樣合理嗎？是否須再去信詢問？
