### ISSUE TITLE
相容區漢字編錯碼

### ISSUE THREAD

**Issue by danny0838** [Jackchows/Cangjie5#129]
https://github.com/Jackchows/Cangjie5/blob/a9694ea05e24873b5fe2e18c239c5a252cdbfaf8/Cangjie5_supplement.txt#L1217
vfvne

https://github.com/Jackchows/Cangjie5/blob/a9694ea05e24873b5fe2e18c239c5a252cdbfaf8/Cangjie5_supplement.txt#L484
jbvif

https://github.com/Jackchows/Cangjie5/blob/a9694ea05e24873b5fe2e18c239c5a252cdbfaf8/Cangjie5_supplement.txt#L127
gfle

https://github.com/Jackchows/Cangjie5/blob/a9694ea05e24873b5fe2e18c239c5a252cdbfaf8/Cangjie5_supplement.txt#L226
fkmbc

https://github.com/Jackchows/Cangjie5/blob/a9694ea05e24873b5fe2e18c239c5a252cdbfaf8/Cangjie5_supplement.txt#L810
nlhem

https://github.com/Jackchows/Cangjie5/blob/a9694ea05e24873b5fe2e18c239c5a252cdbfaf8/Cangjie5_supplement.txt#L1054
shahu

https://github.com/Jackchows/Cangjie5/blob/a9694ea05e24873b5fe2e18c239c5a252cdbfaf8/Cangjie5_supplement.txt#L1257
vyyp

https://github.com/Jackchows/Cangjie5/blob/a9694ea05e24873b5fe2e18c239c5a252cdbfaf8/Cangjie5_supplement.txt#L507
jkia

https://github.com/Jackchows/Cangjie5/blob/a9694ea05e24873b5fe2e18c239c5a252cdbfaf8/Cangjie5_supplement.txt#L1159
yyvin

https://github.com/Jackchows/Cangjie5/blob/a9694ea05e24873b5fe2e18c239c5a252cdbfaf8/Cangjie5_supplement.txt#L884
olhf

https://github.com/Jackchows/Cangjie5/blob/a9694ea05e24873b5fe2e18c239c5a252cdbfaf8/Cangjie5_supplement.txt#L1400
yvfe

https://github.com/Jackchows/Cangjie5/blob/a9694ea05e24873b5fe2e18c239c5a252cdbfaf8/Cangjie5_supplement.txt#L1386
yseq

https://github.com/Jackchows/Cangjie5/blob/a9694ea05e24873b5fe2e18c239c5a252cdbfaf8/Cangjie5_supplement.txt#L434
ilr

https://github.com/Jackchows/Cangjie5/blob/a9694ea05e24873b5fe2e18c239c5a252cdbfaf8/Cangjie5_supplement.txt#L363
heqj

https://github.com/Jackchows/Cangjie5/blob/a9694ea05e24873b5fe2e18c239c5a252cdbfaf8/Cangjie5_supplement.txt#L975
pkua

https://github.com/Jackchows/Cangjie5/blob/a9694ea05e24873b5fe2e18c239c5a252cdbfaf8/Cangjie5_supplement.txt#L128
dhhl

https://github.com/Jackchows/Cangjie5/blob/a9694ea05e24873b5fe2e18c239c5a252cdbfaf8/Cangjie5_supplement.txt#L182
elbn

https://github.com/Jackchows/Cangjie5/blob/a9694ea05e24873b5fe2e18c239c5a252cdbfaf8/Cangjie5_supplement.txt#L659
mfbm

https://github.com/Jackchows/Cangjie5/blob/a9694ea05e24873b5fe2e18c239c5a252cdbfaf8/Cangjie5_supplement.txt#L1136
tnf

https://github.com/Jackchows/Cangjie5/blob/a9694ea05e24873b5fe2e18c239c5a252cdbfaf8/Cangjie5_supplement.txt#L626
lsme

漏字：
```
﨎	yge
﨏	gcor
﨑	uytr
﨓	dtoi
﨔	dfcq
﨟	tbav
﨡	lihqm
﨣	goyj
﨤	ynhe
﨧	cjkd
﨨	cgtj
﨩	nlhau
郞	ivnl
隷	gfle
```

https://github.com/Jackchows/Cangjie5/blob/a9694ea05e24873b5fe2e18c239c5a252cdbfaf8/Cangjie5_supplement.txt#L543
ksh

**Comment by mrhso** [comment]
「﨎﨏﨑﨓﨔﨟﨡﨣﨤﨧﨨﨩」十二字并非兼容字，谢绝钦定。

**Comment by danny0838** [comment]
那些字元的編碼都是在 CJK Compatibility Ideographs 區段，你說不是兼容字是什麼意思？

**Comment by mrhso** [comment]
我不知道为什么在兼容区就是「兼容字」，不如你找找其对应的非兼容字看看？

**Comment by danny0838** [comment]
那要根據什麼定義是不是相容字？

**Comment by mrhso** [comment]
很明显这十二个字符不能表示成某 Unified 字符的 SVS 形式，从而它们本身是 Unified。

**Comment by mrhso** [comment]
![image](https://user-images.githubusercontent.com/13294467/46013795-d656b400-c0ff-11e8-9fec-936041f370f2.png)
![image](https://user-images.githubusercontent.com/13294467/46013811-e8385700-c0ff-11e8-999d-626d1b18c4fa.png)
![image](https://user-images.githubusercontent.com/13294467/46013814-ea021a80-c0ff-11e8-9fdf-efd8ad1e9cac.png)
再者 ISO/IEC 10646 原文就提到了，我的意思很明显了。

**Comment by danny0838** [comment]
所以你們打算怎麼定義相容字？除了這幾個字還有沒有可能有其他相容區的字不是相容字？

**Comment by danny0838** [comment]
"This section" 指的是 "IBM Compatibility ideographs" 那部分吧？我問的是所有相容區的字元中還有沒有其他不是相容字？

**Comment by mrhso** [comment]
没有。

**Comment by danny0838** [comment]
經比對 ffa3721 並沒有修改 `Cangjie5_supplement.txt`，裡面如「索」等字的編碼仍是錯的。是否漏掉了？
