### ISSUE TITLE
靐䨻編碼有誤

### ISSUE THREAD

**Issue by wonghouwing** [Jackchows/Cangjie5#142]
"靐"正確為"mwmww",
"䨻"正確為"mwmww"

**Comment by mrhso** [comment]
http://hanculture.com/dic/v.php?dicword=%E9%9D%90
http://hanculture.com/dic/v.php?dicword=%E4%A8%BB
我不知道你在说，说什么。

**Comment by dupontjoy** [comment]
雷不不是一个整体来取码

**Comment by Jackchows** [comment]
「靐」字首是「雨」，次字首是「田」，次字身是「⿰雷雷」，故取「mbwmw」。
「䨻」字首是「⿰雨雨」，次字首是「⿰田田」，次字身是「⿰雷雷」，故取「mbwww」。
「漢文庫典」中部份疊字使用了新規則，本項目未採用。
