### ISSUE TITLE
EXT C 中 15 字修改

### ISSUE THREAD

**Issue by pttp** [Jackchows/Cangjie5#15]
𪜃  jllu
𪜅  ditt
𪜋  ygjp
𪜌  nsa
𪜎  hlyhn
𪜖  njwsl
𪜘  mrnde
𪜚  endk
𪜜  lmpnn
𪜡  vhyv
𪜣  yciop
𪜥  ywrs
𪜺  ovmi
𪝃  odei
𪝄  okcs

**Comment by Jackchows** [comment]
官方手冊有此項說明：爲了字形均衡而向左撇的“縱”筆畫，取“丨”（縱）而不取“丿”（斜）。
「𪜡」字的第二筆似乎屬於這種情況，因此我認爲「𪜡」取「女中卜女」較佳。
其餘已修改，非常感謝。

**Comment by pttp** [comment]
谢解释，如果用 l (中) 的话，那么其他相似的字也要修改了，现在不太一致∶

**相似字形而取 l 的字**

𠨍  vlsl
𠭛  hwvle

**相似字形而取 h 的字**

𠬞  vhe
𠬳  vhvie
𠂎  hvh
𠬻  qjvhe
𠬿  omvhe
𠭡  hovhe
𠮎  mrvhe
𦥠  hxvhe
𦦒  hxvhe
𭂪  hvhn
𦬥  tvhl
卿  hhhpl
𤼼  novhe
𠃕  lvhu   (参考 U2000.pdf 中的T6-2146字体)

**不太相似而取 h 的字**

𤴴  kvhu

**Comment by Jackchows** [comment]
**𭂪 hvhn**
「𭂪」是「丿㇙」+「几」，故取「hvhn」。
**卿 hhhpl**
「𭂪」从「𠂎」而不从「丩」，我沒有看到「𠂎」有取「中」的字形，因此建議「𠂎」、「𭂪」維持取「竹」，和「卿」一致。
其餘已修改。

**Comment by pttp** [comment]
**卿 hlhpl**
http://www.cns11643.gov.tw/AIDB/query_general_view.do?page=3&code=3a26

**Comment by Jackchows** [comment]
CNS**倉頡編碼**錯誤甚多，且不具有（倉頡輸入法）官方地位，不足為據。
