### ISSUE TITLE
相容區漢字版本及編碼有問題

### ISSUE THREAD

**Issue by danny0838** [Jackchows/Cangjie5#151]
1. `Cangjie5_supplement.txt` 的修改似乎應該放在 ffa3721a8318a77baaae943ab126ec81cbda8427 卻誤植到 69b6abc2a8d65553ebdf1e1f4aeccc5be4675f43 （前者有說修正 #129 卻沒改該檔案；後者沒提到相關 Issue 卻改了該檔案）。

2. 「⺨」應為 ksh 而非 knh。

3. 「𣲼」最早為 ekbn (全碼同)，後來我建議改為 elbn (全碼 elbkn)。但我當時沒考慮到過去有「隺」取碼為 obg 的先例（「人」跨過「月」的輔助字型），考慮此點「𣲼」比照取 ekbn 似乎也合理。或許可考慮問官方或設兼容？

**Comment by Jackchows** [comment]
1.前一次忘記改 Cangjie5_supplement.txt 了，後一次順便補上，總不可能把 ffa3721 回退了重新提交一遍。
2.官方取「knh」。
3.「隺」的「隹」是複合字，似乎有些特殊。

**Comment by danny0838** [comment]
1.一般是把修正獨立為一個commit並寫上適當訊息比較不容易混淆。可以考慮rebase重發，提醒一下大家就好。

2. 原來如此，但官方相似的「豸」取bshh、「豕」取msho，我覺得不太統一；市面上的微軟、雅虎、中標（全字庫）倉頡「犭」都取ksh，我覺得可以考慮設相容碼。

3.我同意兩者有些不同，所以提出來給大家討論一下。

**Comment by Jackchows** [comment]
1. 不想修正。

**Comment by Jackchows** [comment]
3. 未修改。
