### ISSUE TITLE
「𢀓」的取碼

### ISSUE THREAD

**Issue by SyaoranHinata** [Jackchows/Cangjie5#153]
目前「𢀓」取mlsm和xmlsm。但「工」本身是「一」的輔根，不應分拆，參「巫」字。
個人認爲宜改取mss。

**Comment by Jackchows** [comment]
但是「正」也沒有取「一中一」。

**Comment by SyaoranHinata** [comment]
因爲「正」的次碼直接取了「卜」根，更合圈選法（字形特徵）。
可是「𢀓」取「一中尸一」的話，最終還是拆散地取了「一、丨、一」三筆，這三筆沒有根其他的筆畫合併作更合字形特徵的字根啊。

**Comment by Jackchows** [comment]
設了容錯。
