### ISSUE TITLE
其他含倒轉部件或鏡像部件的字

### ISSUE THREAD

**Issue by SyaoranHinata** [Jackchows/Cangjie5#154]
𢇖、𨺅（𤓫、𨼱、𨽄、𨽝、𨽡、𨽩、𨽴、𨽵）、𮗙

**Comment by extc** [comment]
𤒉、
![image](https://user-images.githubusercontent.com/8214015/52656418-46d86300-2f31-11e9-8ff4-991e4c8c51c0.png) (CJK Ext. G 草案WG2 N5006)

**Comment by Jackchows** [comment]
「𨺅」似乎不用「片」也不難取？
（不過「𣥒」、「𫸪」好像也可以不用「片」。）

**Comment by SyaoranHinata** [comment]
「𨺅」不用「片」也不難取，不過目前沒支援對稱形的取碼![image](https://user-images.githubusercontent.com/8178284/52767277-f4985e80-3064-11e9-815d-3a6f2b339b71.png)，只支援其異體寫法![image](https://user-images.githubusercontent.com/8178284/52767263-e9ddc980-3064-11e9-98c8-aa38d0baf970.png)。對稱形若不用「片」，右方首筆宜作「戈」

「𢏽」也有對稱形寫法![image](https://user-images.githubusercontent.com/8178284/52767350-2f9a9200-3065-11e9-96ba-0dabecbccf0b.png)，不過目前只支援非對稱形寫法![image](https://user-images.githubusercontent.com/8178284/52767394-522cab00-3065-11e9-8ceb-3281d1048e7d.png)。可考慮是否也像「𫸪」字般兼容「片式」。

**Comment by SyaoranHinata** [comment]
臦燛臩𦣩𢍴𣥠𣥗𣥄𣳋𦈮𦭢

**Comment by Jackchows** [comment]
已修改。「𨺅」「𣥠」「𣥄」「𣳋」幾個可以直接拆，未使用「片」。
