### ISSUE TITLE
「珁、甄」的次序

### ISSUE THREAD

**Issue by SyaoranHinata** [Jackchows/Cangjie5#156]
「甄」是常用字，有「甄別、甄選、甄拔、甄品、甄錄、甄陶、甄陶天下、甄陶國風」等詞，也是姓氏，如：甄夫人、甄子丹、甄妮、甄嬛、甄寶玉、甄文達等。

「珁」只是「瓷」的異體。

宜改爲「甄」先「珁」後。

**Comment by dupontjoy** [comment]
同意
