### ISSUE TITLE
EXT C 中 20 字修改

### ISSUE THREAD

**Issue by pttp** [Jackchows/Cangjie5#16]
𪝹  oibh ohbh
𪞃  fuahm
𪞇  ogcsh
𪞌  cwywr
𪞙  imyk
𪞚  imso
𪞜  imha
𪞳  hphn
𪟅  imdkn
𪟊  mcsh
𪟒  ysokn
𪟘  omks
𪟢  ttks
𪠖  mtco
𪠗  mdir hdir (在 U2A700.pdf 的字形是 hdir)
𪠰  eeeen
𪠱  segii
𪠺  rqki
𪠿  rh
𪡄  rswl

**Comment by Jackchows** [comment]
𪞌 cwywr
字首「丷」，次字首「田」，故取「金田卜田」。
𪟢 ttks
「益」有兩個字形，故兼容。
𪠗 mdir hdir (在 U2A700.pdf 的字形是 hdir)
兼容不同字形。
𪠿 rh
若按Unicode文檔字形，則右邊不能取「竹」，我認為應該設兼容碼。

其餘已修改。

**Comment by pttp** [comment]
谢解释。我的理解是∶
**𪞌 cwywr**
“丷”跟下方组件，所以上方“𬎿”字首，下面“㐭”为字身。参考字∶
𤎰 cwaf (如果上面c为字首的话，这字便取码cwff)
𤎯 cwaf (如果上面c为字首的话，这字便取码cwff)
**𪟢 ttks**
对于“益”这字，Unicode文档两者都有，现在只取tcbt，所以“𪟢”我认为也可只取tcbt。不过兼容也可以。
**𪠿 rh**
同意兼容，我看到的是 rh，Unicode文字档是 ronn

**Comment by Jackchows** [comment]
𪞌 cwywr
同意修改，是我想錯了。

**Comment by Jackchows** [comment]
己修改。
