### ISSUE TITLE
𤆙？？

### ISSUE THREAD

**Issue by SyaoranHinata** [Jackchows/Cangjie5#161]
無意從 https://github.com/Jackchows/Cangjie5/commit/6561b2de9f891c4ea46da6d7359f2dcacbc87756 中看到這個修改：

刪去：	𤆙	xbsf
增加：	𤆙	xhdtp

好像不太對？從「𤆙」這字形，我看不到怎樣能取「hdtp」。

**Comment by Jackchows** [comment]
手誤。

**Comment by Jackchows** [comment]
已更正。
