### ISSUE TITLE
啊啊啊啊啊啊啊后唱戏，，，

### ISSUE THREAD

**Issue by Arthurmcarthur** [Jackchows/Cangjie5#162]
如题

**Comment by Jackchows** [comment]
爆炸
爆炸

**Comment by Arthurmcarthur** [comment]
![image](https://img.vim-cn.com/fd/8c402bef9510ad5a8c4d7d9024befd192132cb.jpg)

屁聲好好聽！屁味好好聞！太美妙了！

**Comment by InSb** [comment]
我哭了，你们呢，，，
README.md看看怎么改才好。

**Comment by Arthurmcarthur** [comment]
我就音马打自，用力打自，打十万个甚至九万个自
