### ISSUE TITLE
Ext E 中 14 字修改

### ISSUE THREAD

**Issue by pttp** [Jackchows/Cangjie5#17]
𫠠  mp  (lp也可以, 重码忠,jv不太完美，jn 重叠字组件, jp 重叠字组件)
𫠣  knd
𫡳  ttnq
𫢽  omak
𫤌  omhk
𫤲  cryw
𫥮  yuimc
𫦗  nnnnn
𫦘  nesh
𫨀  bwhl
𫪾  rtui
𫫕  rdnq
𫫹  hryhh mryhh
𫯆  icgah

**Comment by Jackchows** [comment]
𫠠 mp (lp也可以, 重码忠,jv不太完美，jn 重叠字组件, jp 重叠字组件)
參考「𭠍(十心)」，我認為「𫠠」取「十女」較好。
𫠣 knd
「漢文庫典」（03五代）「练」字取「女一大女金」，六代取「女一大女木」，「倉頡平台2012」原碼表取「女一大女木」。綜合考慮我認為「𫠣」取「大女弓木」較好。
𫡳 ttnq
同意該改碼。
𫢽 omak
同意該改碼。
𫤌 omhk
同意該改碼。
𫤲 cryw
參考「圖」字，「𫤲」字應該可以設兼容碼。
𫥮 yuimc
@Fktppo 認為此字可取「卜山月金金」或「卜山金月金」，我覺得可行。
𫦗 nnnnn
同意該改碼。
𫦘 nesh
不同字形，應設兼容碼。
𫨀 bwhl
字首「爫」，次字首「罒」，故取「月田中中」。
𫪾 rtui
按規則，「丶」附屬於整個字形，視為一整體字。故「𦍑」字取「廿土竹山/廿手山戈」，「𫪾」取「口廿土戈/口廿手戈」，缺少一個兼容碼稍後補上。
𫫕 rdnq
同意該改碼。
𫫹 hryhh mryhh
「吞」、「彥」都有兩個字形，應該兼容。
𫯆 icgah
同「𫥮」字。

**Comment by Jackchows** [comment]
𫠣 knd
「𠃊」形的轉角並非必須保留，參考「专」、「与」等字，故「东」取「大木」。
「东」和「𫠣」不同，兩字取碼相異不是矛盾。「𫠣」字取碼確實比較難，但考慮「拣」、「练」等字的官方取碼和其他輸入法軟件的取碼，我建議暫時使用「大女弓木」
𫥮 yuimc
若認為「丷」位置比「冂」高，則取「卜山金月金」，反之取「卜山月金金」，與「興」不矛盾。
「兆」是分體字，需要先分割字首字身，字首按筆劃位置高低先取「中」，而「𫥮」是整體字，直接從上到下取「首二三末」，兩者不矛盾。
𫯆 icgah
見「𫥮」。

**Comment by pttp** [comment]
**𫠣 knd**

你的例子说明v(女)是不需要有的。这四字“拣拣练𫍝”中的v(女)有违精简取码原则。我认为可以改knd，如果暂时容错漢文庫典的“大女弓木”，可兼容 kvnd。

**𫥮 yuimc**

有违“興”的取码原则是指应“一”上面的东西从左至右，不是「丷」和「冂」住置，“𠔜 hxlc”是另一例子，中间的l 比 h 高(看U20000.pdf的字)，但先取 h。有违“兆”的取码原则是指字的完整性，左面的冫是一组，右面的“𡿨”是一组，将他们这么远距离拆散再组合破坏字的完整性。不过就算以@Fktppo组合丷
的思路，yubcc,yucbc,为什么不是 yucmc(m指冫里第二笔),或 yubmc(m指同里的一)?还有相似字“楽”也是取iod，若用@Fktppo组合丷的思路，“楽”便要取码cid了。我认为取码“yuimc”比较清徹，字身左上角取“冫”加最后的“八”。

**𫯆 icgah**
見「𫥮」。

**Comment by Jackchows** [comment]
𫠣 knd
「大女弓木」確實不是最令人滿意的取法，但我認為取「大弓木」亦忽略了「𠃊」和「𠃍」左上方有相交處這一特徵。不知道有沒有輸入法軟件編碼「大弓木」，若有，可考慮設兼容，否則我認為應參考「漢文庫典」取「大女弓木」。
𫥮 yuimc
「兆」是分體字，需要先切割成字首字身，「冫丿」為字首，「乚𡿨」為字身，因此左上的「丶」和右上的「丿」無法組成「金」。
「楽」的上方是「冫白𡿨」。假設「冫白𡿨」是一個字，則此字取碼時切割成字首「冫」、次字首「白」和次字身「𡿨」，故「冫白𡿨」字取碼「戈一竹日人」。「冫白𡿨」字在「楽」字中作為字首，取首尾碼，故「楽」取「戈人木」。
而「𫥮」的右邊不是分體字，不必劃分字首字身，所以左上的「丶」和右上的「丿」可以組成「金」。參考「脊」字，「八」被「人」分隔仍可取「金」。
整體字從高到低取四碼，若認為上方的「丷」比「冂」高，則先取「丷」，否則先取「冂」。「冫」的第二筆比「冂」低，故不能先取「一」（即不能取yucmc或yubmc）。
若「𫥮」字存在右側「冂」和「一」分離的字形，則可取「卜山戈人金」。
𫯆 icgah
見「𫥮」。

**Comment by pttp** [comment]
谢分析，我的理解是 ∶

**𫠣 knd**

前面说过，这字有违精简取码原则，「漢文庫典」出错也很多，“凳”便是其中一个，《倉頡平台2012》便容错那个字。你所指的“忽略了「𠃊」和「𠃍」”不知道你如何论证，可否指出手冊中资料？如果等待其他輸入法軟件改了才改，那我便理解错了，我还以为这里改了，其他软件都可以用。

**𫥮 yuimc**

我明白你所说的。我前面举了两个例子说明，“𠔜 hxlc”的例子是说橫线上面不以高底分，取码由左至右。“楽 iod”的例子说明，字首取首尾码是“io”，这两例子指出𫥮 应取yuimc比较好。你说兆切割成字首字身，我明白。楽的字首不可以再分，只拿首尾，手冊有写，而这个字首首码的取码(i)跟𫥮字身首码的取码(i)是一样的。你所说的“假設”在手冊中有写的还是你自己想的？ 「脊」我也明白，这是短距离的拆分，还有“氺”。你说的上方"高低"，有字支持这说法吗？

**𫯆 icgah**
見「𫥮」。

**Comment by Arthurmcarthur** [comment]
有必要提醒的是，手冊並不是完全正確的。誠然，漢文庫典不是完全正確，但也不宜把手冊當成金科玉律，事實上很多隱規則在手冊中是沒有提的。「兆」之所以不能取「金」，是因爲不能跨字首字身取碼，不然「華」就要取「廿廿十」了。這才是「兆」取「中一山人」的原因，而不是因爲距離。距離这東西，不易判定，否則取碼時就要拿個尺子去量距離了。
「楽」的字首取「戈人」，是因爲這字首也是分體的，如果單獨拉出來取會劃成三塊，當然不能取到「金」。

**Comment by Fktppo** [comment]
有必要提醒的是，手冊並不是完全正確的。誠然，漢文庫典不是完全正確，但也不宜把手冊當成金科玉律，事實上很多隱規則在手冊中是沒有提的。「兆」之所以不能取「金」，是因爲不能跨字首字身取碼，不然「華」就要取「廿廿十」了。這才是「兆」取「中一山人」的原因，而不是因爲距離。距離这東西，不易判定，否則取碼時就要拿個尺子去量距離了。
「楽」的字首取「戈人」，是因爲這字首也是分體的，如果單獨拉出來取會劃成三塊，當然不能取到「金」。

**Comment by pttp** [comment]
再分析，回Jackchows, 下面很多问号，请原谅，因为希望大家能对这二字取码有更多认识以至不出错。

**𫠣 knd**

我说的论证是⑴手冊没有支持你的说法？或⑵有没有其他字形取码支持你的说法？

我前面说了，取码 kvnd 有违精简取码原则。想问你，这有没有违你说的“整體字，直接從上到下
取「首二三末」”？ n 高还v高？

现在你说“主流”輸入法軟件了。如果是等其他输入法先改，那么我们讨论是为了什么？

之前我也想过qnd，但没有找到相似字形支持这个q(看手冊)的取法， 而且还有破坏字的完整性的考量 (看手冊)。

**𫥮 yuimc**

关系你的“假设”，手冊没有写是吧？大家尽量跟手冊讨论，否则便会变了个人的输入法。这里依你的说法
“一個字單獨取碼和它作為字首的取碼應該一致”，假设“𫥮 yuimc”的字身是另一字的字首，那么依你的见解，会如何取？

五代手冊第62頁：整體字「字形在四碼以內不能取完，則由上到下，依次取三碼，最後一碼留取字尾，中間部份則略而不取」。

我想问你，这是不是一般不破坏字的整体性情况下的一般法则？还是说对于”𫥮”字字身必须跟从？想听听你的意见，请看第62页和第63页。依你的看法，“𠔜 hxlc”取码是错了？

关于“脊”或“氺”，是关于两点，取码精简性(看手冊)，和字体整体性(看手冊)的破坏性。我所指的远距离柝分是指破坏字整的完整性，楽、率、𠦸等等便例子，在不破坏的情况也是可远距离柝分，如𡢗中的“⺽”。

还有之前讨论你说「丷」位置比「冂」高，則取「卜山金月金」，反之取「卜山月金金」，这里「丷」位置显然比「冂」低，以你的说法，显然不能取“卜山金月金”，为什么你之前又觉得可行呢？

你说“「冫」的第二筆比「冂」低，故不能先取「一」（即不能取yucmc或yubmc）。”，这里的yucmc針对你说不能取的“yucbc”，而yubmc是針对yubcc，yubmc是说你要比较冫的第一笔和同里面“一”的高度吗？ 


**𫯆 icgah**
見「𫥮」。


**回Fktppo，**

我认为手冊说的要尽量跟从，否则输入法便是个人输入法不是仓颉输入法了。漢文庫典只可以是参考。如果你认为字首是分体是一种取法，字首不是分体是另一种取法，还是我说过的，⑴手冊没有支持你的说法？⑵有没有其他字形取码支持你的说法？

**Comment by Jackchows** [comment]
**關於「假設」**
我上面提及的「假設」，都是指假設存在某個漢字。《手冊》不可能窮舉所有漢字，因此任意取一個《手冊》沒有提及的漢字，甚至創造一個新的漢字，都應該可以根據規則取得一個編碼。

**一個字單獨取碼和它作為字首的取碼是否應該一致**
我先前認為應該一致，但後來發現不是。
參考「羋」字，其字首是「<img>」，單獨成字的話取碼「一中中卜」，但在「羋」中作字首取「廿中」。

**這份碼表先改還是其他輸入法先改**
官方碼表中被認為不合理的地方不止「𫠣」一處。例如：為何「冉」取「土月」，而「央」卻不取「大月」？為何「韭」不取「廿廿廿一」？
若將「錯誤」全部改正，做出來的碼表會和官方資料及其他輸入法軟件有相當大差異，以致原本使用其他輸入法軟件的人轉用這份碼表需要再次學習，習慣這這份碼表轉用其他輸入法軟件打字又有困難。一開始我做這份碼表的目的，是從官方、民間主流的取碼裏挑選較為合理的一個，使取碼統一，而盡量避免再添加差異。
具體到「𫠣」字，若確實暫時無法取得一致，我同意設兼容碼。

**「𫥮」**
目前確實看不到「丷」比「冂」高的字形，捨棄「yucbc」，衹討論「yubcc」。
我所說的「yubcc」，是指「yu①②⑤」，①最高，②其次，⑤最低。作字首時，取「月金」。
你說的「yuimc」，我的理解是「yu⑥④⑤」。因為①比④高，所以不能先取④。
你說的「yucmc」，我的理解是「yu②④⑤」。因為①比④高，所以不能先取④。
你說的「yubmc」，我的理解是「yu①③⑤」。因為②比③高，所以不能先取③。
> 这是不是一般不破坏字的整体性情况下的“一般(非绝对)”法则？
若認為從高到低取這一規則必須在不破壞整體性的基礎上才能實行，那麼「乃」就要取「弓尸竹」了。
> 关于“脊”或“氺”，是关于两点，取码精简性(看手冊)，和字体整体性(看手冊)的破坏性。我所指的远距离柝分是指破坏字体的完整性，楽、率、𠦸等等便是例子，在不破坏的情况也是可远距离柝分，如𡢗中的“⺽”。
「冫𡿨」既可拆分為「冫」、「𡿨」，又可拆分為「丷」、「八」。因此我不認為取「丷」破壞整體性。
而「楽」取「iod」，我確實認為其與「羋」取「廿中一十/廿中手」矛盾。
> “𠔜 hxlc”取码是错了？
我認為這是字形問題。

綜上，我建議暫時參考「楽」，取「yuibc」（右側取⑥①⑤），即保持現有編碼不變。

**關於手冊和官方碼表的矛盾**
我的認知是，手冊衹提供了取碼規則的粗略框架。有很多細則是手冊裡沒有說的，但官方在實際編碼時用到了。因此官方手冊和碼表應當互相校檢，不能認為手冊沒有寫的就是不存在的。

**Comment by pttp** [comment]
再分析:

**關於「假設」**

我指的是在手冊里“字首再拆分”是没有的。同一个字结構作为字首取码、字身取码、整体字(你指的单独字)是一致的，全码(手冊)是一样。

**一個字單獨取碼和它作為字首的取碼是否應該一致**

当然要一致，否则很有问题。羋字的字首的全码(手冊)就是 tl，左边跟右边远距离组合成为t(跟手冊的一模一样)。同一个字或结構作为字首取码、字身取码、整体字(你指的单独字)都是一致的，换句话说全码都是一样

**這份碼表先改還是其他輸入法先改**

关于冉央韭，手冊已定下来，除非有大问题，可以兼容，否则都不可以改。我不赞同用“官方”一词，所有码表都不可以叫做官方，只有手冊上印的才可以叫做标准。改变非手冊定的字没有问题，不须容错。从不同码表取合理一个，一定牽涉到分柝，而改变码表，我希望你能夠将错的变成对的，记一堆错码完全没有理由。

**𫠣 knvd**

关于“𫠣”字，前面说过，取码 kvnd 有违精单原则(多馀v)、更有违单線上“上下取码(vn是下上)”原则，所以这取码显然错，论证要小心。我再参考其他网站对于“练”的取码∶

[台湾政府](http://www.cns11643.gov.tw/AIDB/query_general_view.do?page=e&code=525d)∶ vmqd (q字型手冊没有，我认为不可取)

[汉文库典](http://hanculture.com/dic/v.php?dicword=%E7%BB%83)∶ vmkvc (因为n已取钓所以d变了c，有道理，但先v不取n又错了)

[仓颉论坛](http://chinesecj.com/)∶ vmkvc vmkvd (上面说了vmkvd中d没有c好)

从这些参考取码方法，我认为 vmknc 反而最好，不违上下取码，不重叠字型，没有多馀东西。而𫠣字因而应取knvc，knvc比我之前提出的knvd好。

**𫥮 yuimc**

这个字的字身不能用上下尺量方法，Fktppo不是说了，“距離這東西，不易判定，否則取碼時就要拿個尺子去量距離了。”。而yubmc是針对yubcc，yubmc是指, 你要量冫的第一笔和同里面“一”的高度。不破坏字的整体性是指，原本冫是一组，你将它分开是一种破坏。“乃” nsh 或 nhs 是取码次序问题，不是破坏问题。“冫”是破坏问题，否则楽的全码便是cchad了。你为為“𠔜 hxlc”是字形问题，你的意思中间的丨应该比臼短？还是什么？𦥔叟𫌆等等字指出中间的丨是最长的。看第62页和第63页，手冊中的“乖”，作者说明字的“北”是左右取的，还有“坐”，不是上下用尺量的。

**「𫯆」**
見「𫥮」。

**關於手冊和官方碼表的矛盾**

跟手冊。你说的term“官方碼表”是你自己想的，还是有reliable source指出那是“官方碼表”？

**Comment by Fktppo** [comment]
關於「练」问題，我只能告訴閣下，我同Jackchows一樣，認爲「手弓木」最好，而要在「大女木」與「大女金」中選，「大女木」比「大女金」更符區塊原則，六代也是改取了「大女木」。至於爲什麼更合區塊原則，我已經不想和閣下說明了，白費口舌。反正閣下最後只會得出一個結論：其他的編碼都是假的。
如果閣下真的認爲手冊是100%正確的，那請閣下翻到文傳手冊56頁，有一句話：「單純的丨與上相連」。如果「丨」一定上連，那「基帝阜枼」都將成爲連體。
閣下一定要懷疑漢文庫典爲「僞作」，那我就給閣下看一句話：「…２００３年，沈紅蓮小姐因應繁簡字統一編碼的工作，將第五代倉頡輸入法的繁簡版合而為一，名稱仍是第五代倉頡輸入法。…」就我手上有的官方碼表資料來看，其最後修改時間都是2003年9月，與前面我提到的話相吻合，另外，我有一本博碩五倉手冊，它有一附碟，內含擴展基本區、A區編碼，與「漢文庫典」中的相同。既然閣下這麼相信手冊，閣下也應該相信這张光盤才對。要是閣下還是要否認「漢文庫典」編碼是沈紅蓮所作，閣下不妨自認官方，拿着手冊去取每一字。
另外，閣下還沒有回答我和老劉上次提的問題呢？陸標「龜」取「竹難山」是手冊所無，有違手冊所說，奈何吾等倉頡水平不及閣下，那就有請閣下來示範一下拆法吧？「〇」輔助字形爲手冊所無，那「㫈」怎麼取碼呢？我相信，閣下通過翻閱手冊，一定能得出最優結論，而我等人輕信虛假編碼，倉頡水平低下，自當引退了。

**Comment by pttp** [comment]
谢谢意见，首先指出的是我想大家的讨论都是想使仓颉码表更为准确，大家用起来更快乐，记住一大堆错码肯定不会快乐，打不出字更头痛。阿勤的软件改一两个字可能要等几年，改码表更直接。我认为大家的意见是很好的，因为对解码事每个人都会出错，改、不改、改、再改，改到对为止。这仓颉拆字我想就好像科学一样，不可以出错，论证要准确。大家的意见很重要，否则，你错或我错也难以纠正。根据我的估计，这码表还有几千个字编码有问题，要很细心找出来。

**练**

你们认为「手弓木」最好，是不是打错了？q和n重叠字形，是台湾政府的 vmqd 吧？没有弓的。我前面说过，手冊里没有这个上长下短的q，那个q都是上短下长的，我认为除非没办法，否则不应增加辅助字形。对于五代来说，我认为kvd和kvc都有问题 (要n)，理由上面说了。

“基帝阜枼”字都分体，将字放大便可以看到，“干黄焉歹刀”是连体的。对于“卑”，有些字体连有些字不连，不过这个字是分是连都一打法。

关于你提的“凳”，根据手冊，一般来说癶是字首，如“發癹𣔽𤼺”，但根据手冊的意思“登”是字首，如“凳𤼶𤼷𭽃”，你看台湾政府那个码表，这些字一律登为字首，我们会问是不是登最后那个“一”驱使，只有另一个字“𤼬”也有这个“一”，但是否定的。用癶作字首，“登𤼷(ext-b)”会重码。我个人认为这是制造特例，不太好。仓颉论坛的取法是兼容凳，但其他字只取癶为字首。这种字首字身分法很容易出错，我相信是原作者弄错所致。

我说过，漢文庫典只可作参考，如真正台湾政府官方的那个码表，制造码表大家都根据手冊，沈紅蓮小姐也一样，大家都会出错，我指的是，所有码表的错可以改过来就可以，但手冊里写的要小心看待，大家的讨论应是手冊为准。

你说陸標「龜」，是指简写字“龟”？不太明白你指什么。关于一些复杂字，我的见解是找不到完美的，应找个最合适的，违反手冊最少的。对于阿勤编码的古怪字 "𠄏𠄔𠄷𠆭𠇇𠍋𠐲𠚖𠚜𠚡𠥓𠥧𠥩𠥪𠥫𠥬𡄀𡆢𡦹𡧑𢀓𢆴𢍴𢨋𣀨𤒉𤒓𤒜𤓫𤕈𦮙𦲿𦹗𧀍𧥑𧹂𨙨𨛜𨞠𨞰" 还没有看。

**Comment by Fktppo** [comment]
倉頡實際的規則並不是都能在手冊中找到的。手冊只提供了一個基本方法，若一個東西在手冊中找不到，閣下不能說它沒有。閣下也認爲手冊不是全對，這很好。手冊的作用事實上是讓人看了會打字，沒有教人太高深的拆字技巧，「手冊中所無，不應加以引申」這句話本身是存在問題的。
「焉」放大了，中間也有空隙。「卑」若判分連有不同，是不可能同樣打法的，有「竹竹十」和「竹田竹十」兩種取法。關於「丨」上連的問題，手冊並沒有說清楚。
「龜」在港臺標中以「⺈」起筆，手冊只規定了這种寫法的「龜」，那陸標的「丿」起筆的「龜」怎麼辦？當然是類推難字，依從漢文庫典中定的「竹難山」了，不然難道是如同閣下的看法「不應加以引申」，按「基本方法」拆解嗎？CNS有兩個碼表，目前那個網站上掛的是後期的版本，對原作作出了大量修改，沒有什麼價值。

**Comment by Jackchows** [comment]
「关于冉央韭，手冊已定下来，除非有大问题，可以兼容，否则都不可以改」，我的理解是閣下認為碼表較《手冊》所列規則有較高可信度。

實際上，我建立此專案的基本原則，大致可以歸納如下：
一、兩本《第五代倉頡輸入法手冊》（文化傳信、博碩）和「漢文庫典」都是可信的官方資料。
《第二代倉頡輸入法手冊》、《第三代倉頡輸入法手冊》、朱邦復工作室提供的《內碼對照表》（六代），所體現的官方理念，可供參考。
二、《手冊》闡述規則時可能有疏漏，但這些遺漏的規則會在官方實際編碼時體現。因此，碼表較《手冊》所列規則可信。
三、在《手冊》所附碼表的收字範圍外，「漢文庫典」較手冊可信。尤其是「漢文庫典」針對大字符集作出的修改，應採信。若「漢文庫典」和《手冊》附表所收編碼存在差異，則主要採信《手冊》。「漢文庫典」或《手冊》附表內部出現矛盾，則再作討論。
四、對於常用字，盡量依官方編碼，避免修改。不常用字若取碼存在爭議，可適當設兼容碼。

至於完善倉頡輸入法理論、製作一份完全符合《手冊》規則的碼表，**并非此專案的目標，這也超出我的能力範圍**。萬分抱歉，望理解。
若閣下願意建立一專案，根據《手冊》修改碼表，我樂於參與。

我將修改編碼，並在[說明](https://github.com/Jackchows/Cangjie5/blob/master/change_summary.md#主要改碼說明及爭議取碼)中列明理由。

**Comment by pttp** [comment]
testing comment

**Comment by pttp** [comment]
理解你们所说的官方是指“漢文庫典”，好的，等我在这里以你的基本原則讨论。等我有空弄个跟手冊的码表制造，迎欢将来你们来网站讨论、参与。

回答关于陸標的「丿」起筆的「龜」，我终于明白你所说的，那是异体字，如须要，可兼容。

**Comment by Jackchows** [comment]
我說「漢文庫典」**是**官方資料，但沒有說它是**唯一**官方資料。同樣，手冊也不是**唯一**官方資料。

**Comment by pttp** [comment]
谢回答，明白你的意思。

二、《手冊》闡述規則時可能有疏漏，但這些遺漏的規則會在官方實際編碼時體現。因此，碼表較《手冊》所列規則可信。

**Comment by Jackchows** [comment]
我嘗試在README中詳細說明本專案的目標和原則。

**Comment by SyaoranHinata** [comment]
對於「似興」取碼次序，有意見指取「IFBC（丶㇀ㄇハ）」，有意見指應完全按由高至低取「BCMC（ㄇ丷一ハ）」或「BCCC（ㄇ丷ハハ），包含省略」，其實是關乎兩種概念。

第一種，是先把漢字裁成若干個明顯部件，若那個部件要取多碼，仍先取畢那個部件，接着才取下一個。這是倉三的思維。因此「兜」取「HVHU（ノ㇙ノ乚）」，先取完左上角的「HV」；「韭」取「LMMM（〡一一一）」，先取左邊的「非之左半」；「面」下的「囬」取「WYYL（囗⺊⺊丨）」，框內先取完「ㅑ」；「楽」的上方取「IMHAO（丶㇀ノ日𡿨）」，先取完左邊的「冫」，理皆在此。

到了五代，官方似乎想改變思維，變成先把部件都打碎做最基本的倉頡字根，然後完全按由上至下來取，因此「韭」改爲「LSMM（丨ㅑ一一）」，就是如此。但這種更改並不完全，往往有遺漏，例如「兜」在九九五代仍取「HVHU」，至〇三五代才改爲「HSHU（ノコノ乚）」。「楽」字更從來無更改。

竊以爲，若講究規則統一，宜全面檢討有關的字，嚴依其中一式來取碼。若只求與官方碼表融合，則兩種思維的內部矛盾在所難免。

**Comment by Jackchows** [comment]
我傾向於嚴格由上至下取碼，如「韭」取「中尸一一」，「兜」（从儿）取「竹竹女山」（先取「白」的「丿」）。
但是，由於本項目的目標不是完善倉頡輸入法理論，因此常用字暫時依官方取碼。

另外，九九五代手冊「兠」字形从「几」，取「中心竹弓」，沒有收「兠」从「儿」的字形（是否故意不收就不得而知）。

**Comment by SyaoranHinata** [comment]
倉頡並不計算書法裝字上的輕微變形，「兜」上方三個部件應視爲完全平排。與「樂」字一樣，「幺、白、幺」三者平排。

如果嚴格由上至下取碼，「兜」似乎宜取「竹竹尸山」，先是左方「斜匚」的首撇，然後是「白」的首撇，再來是右方的「コ」。現在變成「竹尸竹山」，先取的「竹尸」似乎是「左方『斜匚』+右方的『コ』」，第三碼才到「白」的首撇。不排除是受蒼檢的干預。蒼檢中「左方『斜匚』+右方的『コ』」是直接取「止（X）」的，以蒼檢碼變回倉五碼時，有時會受蒼檢碼的思維影響。

**Comment by Jackchows** [comment]
取「竹尸竹山」更像是將「兜」當成上下分體字。

**Comment by SyaoranHinata** [comment]
不過如果要「嚴格由上至下取碼」，其實「阝」不應取「弓中」，應取「弓尸」。
（純粹按理討論，並不是說要修改編碼）

**Comment by SyaoranHinata** [comment]
說起上來，「幽」是整體字，如果嚴格由上至下取碼，應取「山女女戈」而不是現在的「山女戈戈」。

**Comment by mrhso** [comment]
「幽」是分体字，手册附录有误。

**Comment by SyaoranHinata** [comment]
「直」取「十月山女」而非「十月女山」，「県」取「月山女火」而非「月女山火」，也不是嚴格由上至下取碼。

**Comment by SyaoranHinata** [comment]
剛剛一査「橷」字，採用「⿰木兠」這寫法的話，《漢文庫典》取「木中心山」：
http://chidic.eduhk.hk/v.php?id=7612
換言之是把「兠」的上方視爲次字首，拆作「木.中心.山」了。

同理，「𣘛」字在《漢文庫典》取「木竹尸山」：
http://chidic.eduhk.hk/v.php?id=8722
也是把「兜」的上方視爲次字首，拆作「木.竹尸.山」了。

那麼說來，〇三年五代把「兜」和「兠」的上方視爲可分割作字首了。
