### ISSUE TITLE
漢文庫典的消息

### ISSUE THREAD

**Issue by SyaoranHinata** [Jackchows/Cangjie5#179]
由倉頡維基敎科書主編Ceku兄提供：

小新聞：之前提到網友抓的漢文庫典資料已公開了： https://github.com/danny0838/handict

此外，近期搜尋漢文庫典發現已轉移給香港教育大學【縱橫資訊科技語文發展中心】管理，新網址在： http://chidic.eduhk.hk/
但此中心似乎志在開發另一中文輸入法，不曉得有多少能力及意願維護，也不曉得此站能存活多久就是。

**Comment by SyaoranHinata** [comment]
剛才用了一下，發現版面都變了！

附圖裏的上方是我在11月12日擷的，對比舊的漢文庫典，只是在倉頡碼下方加了縱橫碼，個人覺得還可以接受。

下方則是剛剛擷的。現在卻是把縱橫碼放到倉頡碼上方比加大，個人對這行爲很反感。而且其他各處都擅動過。我眞的很難不憂心！不知未來還會再亂動甚麼！

![image](https://user-images.githubusercontent.com/8178284/70174411-d0029580-170f-11ea-8de1-abec0a9c9cd9.png)

**Comment by marriochoose** [comment]
數學家馬拉錘先生有三大功績：定三死首，否定有義，無敵公式。下面分別講述。

**功績一，定三死首**

> [quote]=官方三代手冊
> 「戊、戈、𢦏、㦰、产、麻、䧹、厭、厤、鴈、辰、厥、羽、府、鹿、亥、老、包、君..等字，雖不能作上下或左右一次分離，然為了取碼方便，一律定義之為字首。」[/quote]

馬拉錘針對官方三代手冊的言論，做了個補釘：

> [quote]=馬拉錘
> 我認為，倉頡三代的複合字首不是活動的，而是像五代一樣，是定死的。[/quote]

至於三死首有哪些，以現在的維基倉教版本為準。

**維基倉教三代複合字首變動史**

20080920 ceku
三：气羽原厭辰麻 䧹府厤（暦上）

20160209 cangjie6
三：增「鴈」

20180718 ceku
三：增「雁」

20180725 ceku
三：增「原厥」

20180905 ceku
三：增「君」

20180921 ceku
三：刪「君」

20200608 ceku
三：增「亥」

20210303 ceku
三：刪「原」

馬拉錘先生（可能）這樣認為：官方三代定死的複合字首以20210303的維基倉教版本為準。已經在這次定死了，不會再增減了。真的是最後一次了！（_而三代官方手冊中一並列舉的「戊、戈、𢦏、㦰、产、鹿、老、包、君」不是三代的複合字首。_）請仍然在世的朱邦復跟沈紅蓮更新官方三代資料！


**功績二：否定有義**

瓦：我們倉頡的目標是，不管一個人認不認識漢字，不管他是中國人，美國人，冰島人，外星人，都能統一用倉頡規則取碼，不需要認識漢字。

對於「㞙」字，如果一個人一眼就看出来它是上尾下水，也不能這樣取碼，否則就違反了倉頡規則。他必須背誦當前的維基倉教三死首版本：
「气羽原厭辰麻 䧹府厤（暦上）鴈雁厥」，然後思考一下「尾」在不在裏面。不在。那麼好了，進入下一個流程。

本流程針對不同字型，參考「懬垕爢㸏」四字，如果（那個字型）左撇下延到底，就取「尸竹山水」，如果沒有下延到底，就取「尸山水」。

不要使用雅倉微倉等老舊的輸入法，它們沒有為「懬垕爢㸏㞙」等字編兩種碼，是錯誤的，是違反官方倉頡規則的。所有人應統一使用三代/五代補完這兩個碼表，因為這兩個碼表是唯一符合了這個規則的碼表。

馬拉錘先生的功績名垂青史，他認為任何漢字只要堅決否定有義字形，就一定能取到正確的字首。在馬拉錘先生看来，倉頡把一切漢字都看成是無義字形，這是最高效的，也是最嚴謹的。

舉個例子：「㖖」字的正確字首是哪個？第一步，堅決否定有義字形，不用管它的字源是「辛口」還是「立古」，否定它！第二步，去查標準字型，查漢文庫典，用眼睛看，看到了吧，它分成了三塊：(亠)(￥)(口)。所以呢它的字首可能是亠或辛。不要斜眼去看其它的字型哦！
![㖖的漢文庫典鏈接](http://chidic.eduhk.hk/m4/y/YLR.BMP)

只要堅決否定有義字形，就能割出正確字首。

「死」字的字源是「歹匕」，但是第一步已經否定了有義字形，之後到第二步，這個第二步用肉眼⋯沒看出来。最終⋯少廢話！反正字首就是歹。馬拉錘會有錯？？馬拉錘是數學家！

㗊型的字，如「麗澀誩競」等，也一律不准用有義字形来割字首，換偏旁法（比如「誩討說話諷」等）也不能用，因為言通常作為形聲字的形旁。那麼用甚麼辦法呢？請看馬拉錘先生的原話：


> [quote]=馬拉錘
> 至於你說的「𧮣」字，取「月金卜口口」較好。倉頡劃分字首字身在這種情況下也是要看我們對漢字的認知的。像「澀」字，標準寫法是寫完「氵」後再寫「刃刃」，再寫「止止」，所以倉頡就取「水.尸戈.一」或「水.尸竹.一」。而像「競」字，標準寫法是「竞」、「竞」，所以倉頡也是從左到右劃成「卜山. 卜廿山」，而不是划成「卜廿.口山.山」。「𧮣」字，先從上把兩個「貝」劃走，然後下部的兩個言，書寫時顯然要寫成「言言」，所以「言」是次字首。
> 
> 不過，「麗」、「䨻」這種字，因為上方的形塊都可一刀切出「一一」、「雨雨」，所以儘管這不符合我們的認知，也只好違反這種認知，取「一一月月心」、「一月田田田」。[/quote]

**功績三，無敵公式**

1-0.1^n這個公式取自馬拉錘先生的文章
[《為何我認為倉頡三代定死了複合字首》](https://www.chinesecj.com/forum/forum.php?mod=viewthread&tid=194378&extra=page%3D3)
：

> [quote]=馬拉錘
> 不妨假設錯碼率是0.1（實際上根本沒有也不可能有0.1那麼高），則八個字全取錯的概率為0.1^8！八個字裏至少有一個正確編碼的概率是1-0.1^8=0.99999999！這麼高的概率也就意味着，這八個字絕對不像某人所說的一樣，是「取錯碼」的！[/quote]


我的理解是，1-0.1^n，n為正整數，當n等於八的時候，「瘱賡螷」等字的編碼絶對無誤。

但是ceku並不同意我的看法，他認為無敵公式不是用来證明「瘱賡螷」等字的編碼絶對無誤的。那麼請ceku講一下，無敵公式1-0.1^n是用来證明甚麼的呢？它還有其它的用處嗎？ceku沉默了。

儘管有ceku等人在歪曲詆毀馬拉錘先生的成就，但經由大家的熱情追捧，宇宙無敵倉頡編碼不出錯率公式1-0.1^n已經是家喻戶曉了。馬拉錘先生不愧是數學界最懂倉頡輸入法的人，也是倉頡界輸入法界最懂數學的人。

如果有人還想試圖貶低馬拉錘先生的數學水平，請看由他發明的世界著名的[馬拉錘數列](https://www.chinesecj.com/forum/forum.php?mod=viewthread&tid=194387&extra=page%3D1)！

> [quote]=馬拉錘
> 經計算可得，f(1)=1,f(2)=3,f(3)=5,f(4)=7,f(5)=114514，所以□内填114514。[/quote]


### 數學家馬拉錘先生的數學水平已經是出神入化了，本人深感佩服！希望大家齊心協力，共同捧起這位倉頡界的大神，創造更多更美好的數學公式！
