### ISSUE TITLE
𫩑（2BA51)的倉頡碼

### ISSUE THREAD

**Issue by extc** [Jackchows/Cangjie5#182]
現在的拆碼是mr（一口）。查𫩑是面的二簡字， 下半部分是囬的外框，
所以應該拆成mw(一田)。
由於CJK Extension G 將會下個月推出, 有一個二簡字30B04 ⿰纟𫩑，（緬）
請到時一倂考慮，謝謝。

**Comment by Jackchows** [comment]
謝謝提供意見。
![图片](https://user-images.githubusercontent.com/10194519/75520451-8a204980-5a40-11ea-8ace-4e05d5294bfd.png)
「口」和「田」區別在於框內有沒有其他筆畫，「𫩑」(U+2BA51)取「一口」無誤。
