### ISSUE TITLE
𢆸𡡤㡭我

### ISSUE THREAD

**Issue by JBRTEarth** [Jackchows/Cangjie5#183]
大概跟碼表無關，請見諒。
1. 𢆸𡡤㡭，倉頡碼是vvii，我打不出來，不知有高手可幫忙解惑？
（內建的倉頡五代也打不出來，碼表都是存在這組碼）
2. 我，此字可以是戈手嗎？我看字源都是右邊高於左邊。

**Comment by JBRTEarth** [comment]
另外，對取碼順序有疑問。
[http://www.cbflabs.com/book/ocj5/ocj5/04.htm](url)
[https://zh.wikibooks.org/wiki/%E5%80%89%E9%A0%A1%E8%BC%B8%E5%85%A5%E6%B3%95/%E5%9F%BA%E6%9C%AC%E5%8F%96%E7%A2%BC#%E5%85%88%E4%B8%8A%E4%B8%8B%EF%BC%8C%E5%BE%8C%E5%B7%A6%E5%8F%B3](url)

**Comment by JBRTEarth** [comment]
還有，倉頡輸入法介紹，說是自康熙字典取碼（節錄一段，1982年，朱邦復在《康熙字典》裏選取四萬多字），然而，有一字拆，明顯不是。
可否能指點一二？

**Comment by Arthurmcarthur** [comment]
1.「㡭𢆸𡡤」取碼「女女戈戈」無誤。如果你在使用Rime，可能是因為你沒有開啓「增廣」選項。
2.「戈」的左上角有物時取碼優先級應高於右上角的點。例：「武」、「載」、「裁」。
倉頡輸入法研發時完全按照字形為考量，以使用者的辨識為重點。勿從字源或字義角度理解倉頡輸入法的取碼，否則容易走入誤區。
3.我認為「也」和「世」都是視作外內形。至於優先級，我認為連體字的取碼優先級是上下>左右，例如「井」取「廿廿」非「手手」。
4.沒有看懂你的意思，不知道你指的是哪個字，為什麼「明顯不是」？

**Comment by JBRTEarth** [comment]
感謝回答！
1. 研究後，設成以下確實可出字㡭𢆸𡡤。
- name: extended_charset
    states: [ 常用, 增廣 ]
    reset: 1 <- 默認開起extended_charset
2. 字源是我誤輸，原本是要打康熙字典。是的，字形與剪字概念。
3. 瞭解，謝謝。
4. 拆，斥。
https://www.zdic.net/hans/%E6%8B%86  請看康熙字典的字形。
照此，是不是取十替卜為好？
4. 我
https://www.zdic.net/hans/%E6%88%91  請看康熙字典的字形。
還是不能理解，若取戈手，是哪裡邏輯錯了嗎？

**Comment by JBRTEarth** [comment]
> 
> 
> 1.「㡭𢆸𡡤」取碼「女女戈戈」無誤。如果你在使用Rime，可能是因為你沒有開啓「增廣」選項。
> 2.「戈」的左上角有物時取碼優先級應高於右上角的點。例：「武」、「載」、「裁」。
> 倉頡輸入法研發時完全按照字形為考量，以使用者的辨識為重點。勿從字源或字義角度理解倉頡輸入法的取碼，否則容易走入誤區。
> 3.我認為「也」和「世」都是視作外內形。至於優先級，我認為連體字的取碼優先級是上下>左右，例如「井」取「廿廿」非「手手」。
> 4.沒有看懂你的意思，不知道你指的是哪個字，為什麼「明顯不是」？

感謝回答！
1. 研究後，設成以下確實可出字㡭𢆸𡡤。
- name: extended_charset
    states: [ 常用, 增廣 ]
    reset: 1 <- 默認開起extended_charset
2. 字源是我誤輸，原本是要打康熙字典。是的，字形與剪字概念。
3. 瞭解，謝謝。
4. 拆，斥。
https://www.zdic.net/hans/%E6%8B%86  請看康熙字典的字形。
照此，是不是取十替卜為好？
4. 我
https://www.zdic.net/hans/%E6%88%91  請看康熙字典的字形。
還是不能理解，若取戈手，是哪裡邏輯錯了嗎？

**Comment by Arthurmcarthur** [comment]
1.朱邦復其時雖然從康熙字典中選取漢字，但在字形上並不跟從康熙字典字形。如在二代手冊和1984版三代手冊中，「今」選取中間作「丶」的字形取「人戈弓」不取「人一弓」，「黃」選取上方作「龷」，中間作「田」的字形取「廿田金」不取「廿一田金」，後來官方雖然修改過幾次取碼字形，但也未按照康熙字典之字形。因此若研究倉頡沒有必要死摳《康熙字典》。
2.我認為「丶」和「丨」的交連不影響是否能取「卜」。「我」的字形，高一點低一點也只是所謂書法上的區別，這一點維基教科書在「忽略書法變形或變位」上也說得很清楚。

**Comment by JBRTEarth** [comment]
> 
> 
> 1.朱邦復其時雖然從康熙字典中選取漢字，但在字形上並不跟從康熙字典字形。如在1984版三代手冊中，「今」選取中間作「丶」的字形取「人戈弓」不取「人一弓」，「黃」選取上方作「龷」，中間作「田」的字形取「廿田金」不取「廿一中金」，後來官方雖然修改過幾次取碼字形，但也未按照康熙字典之字形。因此若研究倉頡沒有必要死摳《康熙字典》。
> 1999版五代手冊第3頁中，有如下記載：「1982年，第三代產品問世…在第三代中，“冫”部与“辶”部同占一鍵…」。可以看出，朱邦復在此所說的「第三代產品」實際上是第二代倉頡，而第二代倉頡輸入法手冊中所選用字形与1984版三代手冊相同，「今」選用中間作「丶」的字形，「黃」選用上方為「龷」的字形，同樣不依《康熙字典》。
> 2.即使真的按照《康熙字典》的字形去取碼，我認為「丶」和「丨」的交連也不影響是否能取「卜」。「我」的字形，高一點低一點也只是所謂書法上的區別，這一點維基教科書在「忽略書法變形或變位」上也說得很清楚。

豁然開朗，再次感謝！

**Comment by SyaoranHinata** [comment]
@JBRTEarth 閣下說「也、世、我」的「右邊高於左邊」，屬書法結字的變形或變位，視乎字體美術設計造型，這些字要是設計成左右一樣高也沒問題，取碼時應當忽略。

維基敎科書有說：
// 忽略書法變形或變位
以「非」字為例，此字是左右平排的組合字，應先取左半，再取右半。有些人習慣把「非」字右旁寫得較高，以求美觀，但這些細微的書寫習慣或書法結字因人而異，取碼時一律忽略不計。//

@Arthurmcarthur 閣下誤會了樓主的問題，他問的不是「弋、式、犮、犬」這類右上方的一點，而是覺得「我」字的「戈」部份（不是一點，是整個「戈」部件）比「⿱㇒扌」部份高。

**Comment by SyaoranHinata** [comment]
@JBRTEarth 另外，閣下說官方手冊的那一段，看例子都可見，說的都是組合字（分體字）。一個組合字，要麼是左右形，要麼是上下形，要麼是外內形，不會同時屬兩形，因此說「由左至右」、「由上至下」、「由外至內」哪個先都沒問題。

但維基敎科書擧的例子，是整體字（連體字）。整體字中，撇除結字問題，必定比較高的部件向來是先取的。敎科書說「巾」先取「丨」後取「冂」已是有力的例子，不用懷疑。Arthurmcarthur兄的「井」也是一個好例子。

**Comment by SyaoranHinata** [comment]
> 「戈」的左上角有物時取碼優先級應高於右上角的點。例：「武」、「載」、「裁」。

請容在下更正Arthurmcarthur兄的字例。
如果只是說右上角的一點，在取碼時必然把那一點視作最高，優先取它，例：「犮、犬、弋、式、貳、甫、求」。
但若是整個「戈部件」而不只是一點，可以有其他部件位於「戈」的上方，那麼就會最先取那上方部件，之後才取「戈部件」。例如「哉、載、裁」的字首「𢦏」都是「十戈」。又如「㦰」是「人人戈」，「韱」是「人戈.中尸一」。
至於「武」字比較複雜。如果是「式」，字首是「弋」，一點必然位於最高，取「戈心（丶𫠠）」。但「𢍼」的「一」位於「弋」上，因此取「一戈心」，以它爲字首的「武」則取「一心.卜中一」。

P.S.內文的「𢍼」指的是這個字形： http://glyphwiki.org/wiki/cdp-8cb8-var-001

**Comment by JBRTEarth** [comment]
> 
> 
> @JBRTEarth 另外，閣下說官方手冊的那一段，看例子都可見，說的都是組合字（分體字）。一個組合字，要麼是左右形，要麼是上下形，要麼是外內形，不會同時屬兩形，因此說「由左至右」、「由上至下」、「由外至內」哪個先都沒問題。
> 
> 但維基敎科書擧的例子，是整體字（連體字）。整體字中，撇除結字問題，必定比較高的部件向來是先取的。敎科書說「巾」先取「丨」後取「冂」已是有力的例子，不用懷疑。Arthurmcarthur兄的「井」也是一個好例子。

多謝兄台熱心講解，謝謝。
