### ISSUE TITLE
JSON

### ISSUE THREAD

**Issue by cbaTW** [Jackchows/Cangjie5#184]
不曉得J大有沒有辦法將txt轉成json的結構？

**Comment by Jackchows** [comment]
我嘗試一下。

**Comment by Jackchows** [comment]
超級拖延症🫣
程式見https://github.com/Jackchows/Cangjie5/blob/master/scripts/buildJson.py
但願幫到原po或者其他人😂

**Comment by danny0838** [comment]
提一點程式優化的小建議：

1\. JavaScript/JSON 如果要縮排，目前大多習慣用 2 個空格，參考 [Google JavaScript Style Guide](https://google.github.io/styleguide/jsguide.html#formatting-block-indentation)。

不過不確定這裡的輸出是否要給人閱讀，如果只是純粹供程式讀取，可考慮不縮排及最小化輸出，即 `indent=None` (預設值可省略)、`separators=(',', ':')`。參考[官方文件](https://docs.python.org/zh-tw/3/library/json.html#json.dump)。或者另外加個命令列參數讓使用者決定是否最小化輸出。

這裡的資料格式應該不可能含有循環參照，可考慮加上 `check_circular=False` 省略不必要的運算以提高效能。

2\. Python 讀寫檔案一般建議寫法是用 context manager：

```Python
with open(github_file,'r',encoding='utf8') as gib,\
     open(json_file,'w+',encoding='utf8') as jsn:
    ...
```

context manager 結束時即會自動 close，可以省略 call close()，更重要的是在內部程式碼出錯時也會自動 close。雖然對小程式而言，出錯中止時也會自動釋放資源，因此差別不大；但如果是出錯時不會中止的常駐大程式，沒有 close 就會造成檔案讀寫被卡住。

以上多個 open 寫法可改用更建議的括號跨行，但 with + 括號在 Python 3.10 才開始支援，如要相容舊版還是只能用 `\`。參見 [PEP8](https://peps.python.org/pep-0008/#maximum-line-length)。

**Comment by Jackchows** [comment]
多謝指教。
4. 最初的想法是用正規表示式排除txt開頭的說明文字，然後再split。
想了一下，改成`^([^\t\n\r]+)\t([a-z]{1,5}).*$`似乎可以滿足需要。

**Comment by Jackchows** [comment]
我再研究一下。

**Comment by danny0838** [comment]
剛才又看到幾個比較大的問題：

1\. 最近的 commit 中 buildTxt 整個縮排大亂，似乎是編輯器誤混入了 `\t` 作為縮排字元。

2\. 檔案路徑處理盡量用 Python 內建的 [`os.path.*`](https://docs.python.org/zh-tw/3/library/os.path.html)，目前有很多諸如 `current_directory+'\\'+github.replace('.txt','.json')`，其中 `\\` 是 Windows 專用的路徑分隔字元，Unix/POSIX 都是用 `/`，這樣寫會導致程式只能在 Windows 系統上跑，失去了 Python 跨平台的優勢，也會影響以後寫 GitHub workflow (通常也是用 Unix/POSIX 系統)。
