### ISSUE TITLE
碼表中似無B區新增的幾個公(×工)尺譜字

### ISSUE THREAD

**Issue by Hulenkius** [Jackchows/Cangjie5#185]

**Comment by SyaoranHinata** [comment]
請問碼位在甚麼地方？

**Comment by SyaoranHinata** [comment]
http://glyphwiki.org/wiki/u2a6dd
http://glyphwiki.org/wiki/u2a6dd

**Comment by SyaoranHinata** [comment]
找到了，應該是「工尺譜」才對。是「合、四、一、上、尺、工、凡」末尾各加一小鈎。
個人建議當作一般漢字拆形，順序爲「OMRN、WCN、MH、YN、SOH(/SON)、MN、HNI」。

http://glyphwiki.org/wiki/u2a6d7
http://glyphwiki.org/wiki/u2a6d8
http://glyphwiki.org/wiki/u2a6d9
http://glyphwiki.org/wiki/u2a6da
http://glyphwiki.org/wiki/u2a6db
http://glyphwiki.org/wiki/u2a6dc
http://glyphwiki.org/wiki/u2a6dd

**Comment by Jackchows** [comment]
謝謝提醒。三個txt有的，release 版本漏了。

**Comment by Jackchows** [comment]
已發佈。
