### ISSUE TITLE
𪚨

### ISSUE THREAD

**Issue by SyaoranHinata** [Jackchows/Cangjie5#186]
現時「𪚨」取「jcmxu」，但那個「x」有爭議吧。
個人建議取「jc.mu.w」。

**Comment by Jackchows** [comment]
參考[「𪚾」](chidic.eduhk.hk/v.php?id=35851)[「𪚧」](http://chidic.eduhk.hk/v.php?id=35854)[「𪚿」](http://chidic.eduhk.hk/v.php?id=35852)，可取「jcmsw」。
