### ISSUE TITLE
Unicode 13.0在Ext.G外的新增漢字

### ISSUE THREAD

**Issue by SyaoranHinata** [Jackchows/Cangjie5#187]
目前Unicode 13.0的公佈，除了擴展區G外，在其他漢字區也新增了一些漢字，但目前碼表還未支援。除了另一位朋友提及的工尺譜用字外，還包括：
急用科學與技術用字（U+9FF0–U+9FFC，鿰鿱鿲鿳鿴鿵鿶鿷鿸鿹鿺鿻鿼）
10個需分離的漢字（U+4DB6–U+4DBF，䶶䶷䶸䶹䶺䶻䶼䶽䶾䶿） 
有勞了！

**Comment by SyaoranHinata** [comment]
此外也問一問，有幾個日本年號合字：㍻、㍼、㍽、㍾、㋿，不知也會不會增加？
建議字碼：
㍻ MJIHS
㍼ ASRR
㍽ KMYM
㍾ ABER
㋿ OLHDR、OIHDR

**Comment by Jackchows** [comment]
那幾個年號有的，不過要打「zf」開頭。
新增的字也有的，三個 txt 裡有，release 版本漏了遲點補。

**Comment by Jackchows** [comment]
已發佈。
