### ISSUE TITLE
Ext F 中 17 字修改

### ISSUE THREAD

**Issue by pttp** [Jackchows/Cangjie5#19]
𬺸  tvs
𬺺  lks
𬻇  mll
𬻒  pbs
𬻔  mbmi
𬻞  bssm
𬼀  ih
𬽋  yoou
𬽕  ywlv
𭀃  tolwk
𭀜  vviu
𭀝  myu
𭀤  ttcu
𭁐  omlc
𭁒  bnc
𭂾  macu
𭃌  qmsh

有些字比较复杂，可以讨论。

**Comment by Jackchows** [comment]
𬺸 tvs
參考「平」字橫切，我認為可以取「火十女尸」。
𬺺 lks
橫切，故取「中十女尸」。
𬻇 mll
不明白此取碼。
𬻒 pbs
「𫠠」不是特殊字，故「𬻒」除去「𠃌」的部份應切割。
𬻔 mbmi
同意修改。
𬻞 bssm
同意修改。
𬼀 ih
按高低，先取「竹」。
𬽋 yoou
同意修改。
𬽕 ywlv
同意修改。
𭀃 tolwk
𭀜 vviu
按高低取「女女竹山」。
𭀝 myu
同意修改。
𭀤 ttcu
參考「発」字，故取「廿大心金」
𭁐 omlc
參考「兼」字，應取「人一難金」
𭁒 bnc
同意修改。
𭂾 macu
同意修改。
𭃌 qmsh
同意修改。

**Comment by pttp** [comment]
𬺸 tvs
例子“平”可用f，但这里是斜的，不应用f ，有违手冊所例的f。

𬺺 lks
参考“亐 mks”，不应用“十”。这里的“中”也是斜的，其实也有点违手冊所说，但好像没有其他取法更好。

𬻇 mll
第一个l是中，第二个l是“丨”

𬼀 ih
不应取高低，参考“为州⺖”，倉頡論壇以前好像有人说这种字方向是左上角至右下角。

𭀜 vviu
同𬼀，左上角至右下角取码

𭀤 tkpc -> ttcu
同意不改码。

𭁐 omlc
这字好像有违手冊所说，等我再想想。

**Comment by pttp** [comment]
𭁐 omlc
根据“官方”取法，对于你的码表，同意不改码。

**Comment by Jackchows** [comment]
**𬻇 mll**
參考「丳」字，取「一中中田」。

**Comment by SyaoranHinata** [comment]
> 𬻞 bssm
> 同意修改。
等等，依據「𠕄」，應取SSLM

**Comment by Jackchows** [comment]
「𠕄」若先取「月」，將變成「月月一一」，不如「尸尸月」精簡，故不取「月」。
而「𬻞」：①先取「月」，全碼「月尸尸尸尸中中一」②先取「尸尸」，全碼「尸尸尸尸尸尸中中一」（我認為此處第三碼不能取「中」）。①較精簡。

**Comment by SyaoranHinata** [comment]
竊以爲，以倉頡處理「類亞形」的習慣，「𬻞」若先取「月尸尸」，接下來就會剩下「中中一一」，即（└ ┘）之形，然後才接「中中一」的底座。不見得會在「月尸尸」後留下少許，讓下方以（[ ]）形取「尸尸」。不過這點的確無官方碼作證據，因爲不論何字，取到這裏皆已省略掉。

**Comment by SyaoranHinata** [comment]
個人並不以爲然。倉頡取碼中，字形特徵勝於精簡。字形特徵中有對稱分則，當中「亞 減去 二」正是要應用此則的形塊，拆作「中中尸尸中中」，因此「亞」字才會是「一中中尸尸中中一」，省略後即「一中中一」。若要以精簡凌駕字形特徵，爲甚麼尾碼不是「廿」？爲甚麼第三碼的「中」不是「女」呢？

現在「𬻞」字同理，若要最精簡，尾碼也應該是「廿」而不會是「一」。現在顯然不是以精簡凌駕字形特徵，故取「尸尸中中尸尸中中一」，省略後即「尸尸中一」才合理。否則就跟「亞」字自相矛盾了。

還是要連「亞」字也一併修改，變成「一中女廿」，以精簡凌駕字形特徵？那麼「𬻞」字才可以一樣以精簡凌駕字形特徵，取「月尸尸廿」（結果仍然不是半桶水精簡、半桶水字形特徵的「月尸尸一」）。不過，這樣做的的，連「之」等其他字也很可能一樣要改啊。

**Comment by Jackchows** [comment]
![2cede](https://user-images.githubusercontent.com/10194519/36624158-dc51cef0-1946-11e8-86e1-fa1c8f1f0680.png)
①、②皆對稱分拆，而①少一碼，為何取②不取①？
①和②相比損失了甚麼字形特徵？

**Comment by SyaoranHinata** [comment]
損失了「亞 減去 二」部份的上下對稱啊。

若只要左右對稱便行，「亞」大可取「一中中廿」呢。

**Comment by Jackchows** [comment]
「亞」字本身是上下對稱，而「𬻞」字不是啊。
而且我不覺得上下對稱就要對稱取，不然「丰」要取「十十十」？

**Comment by SyaoranHinata** [comment]
如果這樣的話，「亞」字就應修訂作「一中中廿」才做法一致啊。
（雖然我知這計劃並不會。只是論事而已。）

**Comment by Jackchows** [comment]
我覺得「亞」可以改「一中中廿」。（當然這計劃不會改。）

**Comment by SyaoranHinata** [comment]
像大新倉頡等直接把「亞 減去 二」作「難」的輔根，這就減少好些爭議。
（也是並非說本計劃吶）看來這做法也可取，而且也應該有不少認同吧？

**Comment by Jackchows** [comment]
如果加根，「壺𡔳𡔲𡕈」也能用上。

**Comment by SyaoranHinata** [comment]
對啊，還有「𡸭𠤛」也可以。
說起來，其實蒼檢也設了這個根，是「止」的輔根。當初倉頡不設，可能覺得除「亞、壺」外其餘都是罕用字吧。但其實「亞」部件的字也不少，「爲何尾碼不取廿」此問題也困惑過我良久。加這根是實用的。
