### ISSUE TITLE
漢文庫典內容遭篡改

### ISSUE THREAD

**Issue by SyaoranHinata** [Jackchows/Cangjie5#190]
漢文庫典是官方（朱邦復工作室）2003年版五倉的取碼標準。
在issue #179裏說過了漢文庫典轉移給香港教育大學【縱橫資訊科技語文發展中心】管理的消息。
當是我擔心過，由不熟諳倉頡的團隊管理會否出岔子。
不幸的是，剛剛發現擔心成眞了。
4月29日我回應issue #17時，我還查過「兜」字的2003年取碼是「竹尸竹山」。無論這是基於甚麼方式去取碼，這是2003年取碼的長期結果。
但剛剛的查詢結果，卻發現「兜」字的倉頡碼被篡改成1999年版的「竹女竹山」！而且也不見網站有任何說明！
這事態嚴重，等於在悄悄偷換朱邦復工作室的實際成果，混淆各版本，令大家或進也好或退也好都失據。
希望我們能聯合起來，投書朱邦復工作室及現時的管理方，讓其知悉問題之嚴重，撥亂反正！

http://chidic.eduhk.hk/v.php?dicword=兜

(本文亦發到倉頡之友論壇 http://www.chinesecj.com/forum/forum.php?mod=viewthread&tid=194469 中)

**Comment by mrhso** [comment]
我个人以极大的恶意揣测，此事为 E****n 所为，虽然只是我个人的看法，但是这种可能极大。
猜测是某位写信给 EdUHK 造成的后果。这种行为是极为可鄙的。

**Comment by Arthurmcarthur** [comment]
雖然沒有更直接的證據，我也認為是E****n所為。事態嚴重，我參加聯名。

**Comment by InSb** [comment]
希望向朱邦复工作室和縱橫資訊科技語文發展中心这两方去信询问。

**Comment by mrhso** [comment]
此事性质过于恶劣，先置顶了。

**Comment by wcshds** [comment]
這種行爲太惡劣了，應立卽向朱邦復工作室抗議。

**Comment by Jackchows** [comment]
參與聯名，需要向朱邦復工作室確認是否有授權縱橫中心修改漢文庫典的內容。

**Comment by Fszhouzz** [comment]
支持詢問工作室，請其查究原因並改正。如果有力所能及的，我後續也都關注和支持。

**Comment by cangjie6** [comment]
這篡改應該是自本年4月起再次發瘋的妄想症玄學家尹卂(ejsoon)所為，這事並非沒有證據。

[url=http://www.chinesecj.com/forum/forum.php?mod=viewthread&tid=194363]像錘子所言，[/url]他曾針對「兜」字的五代取碼给沈红莲致信。可見同類事件，那玄學家早已做過，再犯並不為奇。

尤其是那玄學家近年的言論，已完全把「兜」的2003版編碼視為「錯碼」，全世界所有人眼中的篡改，在他一人眼中卻是改正錯誤：
![image](https://user-images.githubusercontent.com/66377216/83657795-e8d30180-a5f3-11ea-9280-619c631da333.png)
(翻攝自： http://ejsoon.win/pb33/viewtopic.php?f=6&t=1534 )

而且自去年年底漢文庫典發現已轉移給香港教育大學【縱橫資訊科技語文發展中心】管理後，那玄學家甫知道消息，就已經企圖去信給【縱橫資訊科技語文發展中心】要求改動漢文庫典的資料，還第一個針對「兜」字，如下：
![image](https://user-images.githubusercontent.com/66377216/83657826-f7211d80-a5f3-11ea-8776-1a26c4af6a58.png)
(翻攝自： http://ejsoon.win/pb33/viewtopic.php?f=3&t=1349 )

儘管在同一討論帖下，ichirou力陳要害，極力阻止，但他不但毫不在乎，更在3月2日特地把【縱橫資訊科技語文發展中心】電郵抄出來：
![image](https://user-images.githubusercontent.com/66377216/83657845-fe482b80-a5f3-11ea-996b-15161f8fa406.png)
(翻攝自： http://ejsoon.win/pb33/viewtopic.php?f=3&t=1349 第2頁)

而更直接的證據是，ichirou在4月30日回覆了「倉頡五代補完計劃」的issue #17，同時也[url=http://www.chinesecj.com/forum/forum.php?mod=viewthread&tid=194382]在倉頡之友論壇發帖講述ichirou對「兜」等字的看法[/url]後，那玄學家很短時間就把ichirou的發言抄到他自家的煉蠱穴中，並私下反駁ichirou的看法：
![image](https://user-images.githubusercontent.com/66377216/83657936-1fa91780-a5f4-11ea-9e5a-25b3d729f46f.png)
(翻攝自： http://ejsoon.win/pb33/viewtopic.php?f=3&t=1489&p=7254 ）

從反駁中可見，那玄學家不但不能接受「竹尸竹山」是有道理可依的取碼，還把漢文庫典攻擊作「漢文痛典」，甚至更已陰險卑鄙奸計得逞的口吻說：『你們可以再去查一次漢文痛典的「兜」…（嘻嘻） 』要不是他知道「兜」字在漢文庫典中已被或即將被篡改，他這句話是無法有合理解釋的。

由此可見，這次卑鄙陰險的篡改，是那個以扭曲倉頡、指鹿為馬的玄學家尹卂所為。

我，「維基教科書：倉頡輸入法」編輯Cangjie6，在此表明參與聯署。同時，我在思考是集體聯署比較有效，還是各人都分別投寄信件比較有效。無論如何，我們可以起草一份書信藍本，作爲大家的初稿。

**Comment by chowhoyin** [comment]
表示關注，參與聯署。支持向兩方詢問覈實。

**Comment by ejmoog** [comment]
請問是聯署繼續更正「兠蔸」等字的編碼例推，還是改成原来的錯碼「竹尸竹山」？

附：如果「兜」取作「竹尸竹山」，有以下幾個問題：
一，儿一直有上聯功能，未見不能聯者；二，若取消儿的上聯，那麼該撇就要還原為縱撇；三，字源支持兜為連體，同「允充」等字；四，兜的初始字型，即宏碁天龍字型和聚珍字型，都是連體字，很多字至今仍適配初始字型，如「歿沒」；五，若倉五碼表編碼者可以擅自取消儿的上聯作用，那麼虍就沒必要再設為複合字，因為只要擅自取消「虎」字的儿上聯就可以了。

**Comment by cangjie6** [comment]
有人自己寫完回應，自己給自己按反應。可憐哪。

倉頡拆字，根據是字形，不是字源。樓上那個唯恐天下人不知道他的身分假名的篡改賊，繼續沉迷他的字源取碼玄學，完完全全不是來討論道理，而是來宣傳他當教主的一人邪教。倉頡是可以爲各異體字設立編碼的。像樓上玄學家舉出的「歿、沒」，漢文庫典早就為不同字形設立相對應的編碼。難道又要被樓上那個無恥玄學家視為『錯碼』嗎？
![image](https://user-images.githubusercontent.com/66377216/83954149-1aa8ca00-a879-11ea-8af1-e962586b435f.png)

「夋夌𡕩」等字中間的「ㄦ」確實與其上的橫向筆劃視爲相連。可是「允充虎」等字下方的「儿」是否如此，從編碼不能判斷，因爲它們的取碼結果會是一樣的。玄學家以「允充虎」作為論據，真是可笑。「ㄦ」和「儿」並不是同一個字形，官方手冊已說明。「儿」是否與其上的橫向筆劃視爲相連，得視乎官方在該版本裏的處理。從取碼結果得知，1999年版是處理成相連的，2003年版是處理成不相連的。我們也沒有道理支持若「儿」不視爲與其上的橫向筆劃相聯就要取「中」不取「竹」。玄學家卻還是沉迷在自己的妄想玄學中。

**Comment by ejmoog** [comment]
有人自己寫完回應，自己給自己按反應。可憐哪。
------
ej:本人第一次在github上作評，新手上路還請多多指教。不過那個「反應」功能該如何按，能不能按，恐怕這屬於個人的自由。某地通過了某安法之後，君以後再敢隨便亂說話點個讚可能都會出問題。我在此支持並祝福你們。
[end]


倉頡拆字，根據是字形，不是字源。
------
ej:倉頡拆字是根據字源而非字形。因為字源包含字形變化，而字形有時能體現字源，有時不能。比如說「改頑辣邦」的字首尾碼，「界」第二碼識別為「人」，「婁」堅持取「中」，等等，這些都是靠字源在還原字形，靠字源去「記憶」字形。而一旦字形發生了過份實質的變化，不是「微調」能調回来的，倉頡也承認這種變化，比如踢，足𧾷相差過大，現今通行的倉頡就沒有還原。它的微調是有限的，這是官方規則的一部份。

同時倉頡字元是以一帶百的，因此可以應用到任何字集。不會像其它輸入法要根據字集而調整字根，或說某輸入法就是為某字集專門設計的。這也是倉頡體現字源的一個方面。（但是不包括倉頡五代，從它把「合薛」定為複合字首這一做法来看，五代是為九〇版聚珍內碼定制的倉頡版本。）

那麼倉頡為甚麼要體現字源？它不體現字源不行嗎？因為字源是唯一的，字形是多變的。不同的字體作者有不同的愛好與習慣，比如腐字有些字體是上下分體，有些字體是左撇向下延伸。因此在倉頡的結構判定中，延伸要看作沒有延伸，為的是要體現字源。腐字一撇下延你就看不出它是形聲字了？那是智商太不夠用了。

也就是說倉頡能在一定程度上符合字源，它不是完全能符合字源，也不是完全不符合字源。倉頡在字元辨識和結構判定這兩個環節上可能會用到有義字形，但是一個楷書漢字是否能符合字源，這不是倉頡能控制的，倉頡只能控制它的職權範圍之內的事。

因此「兜」字如果有字源旁證，和允充皃兒等字同源同形，那它就屬於符合字源的那一部份。不是說「因為有一部份字不符合字源」，「所以今後在倉頡取碼討論中堅決不能談字源」，字源是可以談的，有大量漢字編碼的旁證支持。

君可能對字源的理解有誤，或是對字源的理解與我有所不同，我也不知道各位哪裏来的對「字源」有如此巨大的偏見。倉頡原名形意輸入法，因為還不夠（體現它符合字源的特性），因此蔣緯國賜名倉頡。

倉頡乃至所有形碼的設計與研製目標都是最大限度的實現無重，無重就是唯一準確的編碼。今日你們連字源是甚麼都搞不懂，連「兜」的正確編碼是甚麼都搞不懂，怎麼能做到「唯一準確」呢？那不是給徐碼等能做到唯一準確的形碼輸入法的作者及用戶笑話嗎？
[end]


樓上那個唯恐天下人不知道他的身分假名的篡改賊，繼續沉迷他的字源取碼玄學，完完全全不是來討論道理，而是來宣傳他當教主的一人邪教。
------
ej:本人一向硬核回覆，踏實研究，有根有據，道理清晰。恐怕搞玄學和迷信的另有其人。

玄學是朱邦復工作室的風氣，朱邦復自述早年在巴西有一束光照到他身心，然後他「得道」了。從沈紅蓮的回覆来看也不是一個正常人的表述。朱工作室還有鴻鵠爪泥等版塊，都在大談玄學，自創宗教，在我看来是極其可笑的。

一方面某些人自己就找到了很多漢文庫典的錯碼，另一方面要堅決保護庫典的貞潔，只要是想改漢文庫典就是搞破壞，就是出於惡意，就是惡劣。這不是迷信是甚麼？

君以為朱室還有高手嗎？據本人多年觀察，朱室沒有任何營利項目，因此在朱邦復病後，他們把庫典當成個字典拿去賣，賺一筆朱室最後的運營資金和朱邦復醫療費。朱室因為過於清貧，工作時間超長，還要求週末時間要聽朱的「講座」，一講就是一個下午或一個晚上，玄玄叨叨，沒有意義。既不可能修成正果走出三界，連修養身心祛病健身都做不到。因此人心渙散，沒有人願意待下去，我猜測朱室早就人去樓空了。

從朱室回覆来看，朱室根本沒有高手。因此在最艱難的時刻，他們作出了最艱難的決定，賣掉能賣的東西，找了半天好像就只有漢文庫典拿的出手，那是一個字源字典，也叫玄談字典。

諸君擔心香港教育學院的人不懂倉頡，我從他們的回覆来看，水平不知比朱室高多少。諸君如果真的認為只有朱室工作人員配改漢文庫典，就集資湊錢去把漢文庫典買回来，並維持庫典的運營，不要廢話連篇，大搞玄談。
[end]



倉頡是可以爲各異體字設立編碼的。像樓上玄學家舉出的「歿、沒」，漢文庫典早就為不同字形設立相對應的編碼。難道又要被樓上那個無恥玄學家視為『錯碼』嗎？
image
------
ej:倉頡是做不到為每一個異體字型設立編碼的，比如「產産兼歿」，都已經寫入了倉頡的初始基因。倉頡一開始是朱邦復買了幾本國語字典去做的，字型基本上是那時的舊臺標字。朱邦復自述他在做三代時，康熙字典上有「見於xx墓碑」的字，他一律拒收。

漢文庫典的內碼是聚珍內碼，聚珍在unicode推之後可能為其做了兼容，但unicode反過来並沒有收錄聚珍內碼。因此目前只有聚珍收錄（或說自製）某些奇特的字型和編碼，比如說「兩種麻」，幾種「執」，那都是聚珍自己的內碼。

是否視為「錯碼」那就看你用的是甚麼機。如果您用的是倉頡機，那裏面是聚珍內碼，這樣你用漢文庫典查到的哪個編碼都是對的。如果您在unicdoe環境下也妄想去兼容聚珍內碼，是對是錯您自己去判斷吧。
[end]



「夋夌𡕩」等字中間的「ㄦ」確實與其上的橫向筆劃視爲相連。可是「允充虎」等字下方的「儿」是否如此，從編碼不能判斷，因爲它們的取碼結果會是一樣的。
------
ej:同意。
[end]


玄學家以「允充虎」作為論據，真是可笑。「ㄦ」和「儿」並不是同一個字形，官方手冊已說明。「儿」是否與其上的橫向筆劃視爲相連，得視乎官方在該版本裏的處理。從取碼結果得知，1999年版是處理成相連的，2003年版是處理成不相連的。
------
ej:沒有所謂的「官方」，都是人做的。理論上我們可以有名有姓的指認是哪一位工作人員編了哪一個字的碼，但是由於朱室過份清貧，沒有營利，在深圳這種地方做玄談字典根本沒有立錘之地，發不起工資，招不到工人。因此根據沈女士的一些回覆来看，漢文庫典他們早就改不動了，早就托付他人了，沈說「漢文庫典的編碼不是我做的」，我又沒問是誰做的，她怎麼這麼心虛。

將庫典分成九九版和〇三版，那是您自己的想法。〇三年到現在都多少年了。我猜他們九九年招到某員工，於〇三年辭職，以後招不到工了，因此〇三年之後庫典就不改了。你們竟然堂而皇之的把錯碼連篇的漢文庫典視為聖經，又把它跟倉五手冊相左的地方稱之為新版五代，叫〇三五，那不是矛盾嗎？那不是笑話嗎？如果徐碼也有一個一〇徐碼，一二徐碼，兩種徐碼編碼不一樣，那不是很可笑嗎？漢文庫典查到了幾多錯碼，生造出幾多脫離實際的字型圖檔，你們自己都講那是六代改来的，它是三代改還是六代改都好，反正有很多漏改的，漏改的那些錯碼，就是〇三五新版本規則？

你們現在見到「官方」被「惡劣」的改掉之後慌了手腳，氣急敗壞，因為它破壞了官方的「那個版本」的純潔與完整（完美一詞就不敢用了）。多年来庫典有這麼多錯碼改不動，說它是頑固還差不多。

在「官方某位工作人員」的個人編碼失誤或對規則理解有誤的情況下，他為「兜蔸」等一系列的字編了錯碼，然後你把他編的錯碼說成是「倉五有新規，儿可不上聯」，那是你自己的理解，不要把你自己的理解強加給別人。有很多人還買不到倉頡機，下載不到符合新規的倉五碼表。現在既然「新官方」把「兜」改回了之前的正確編碼，說明「新官方」認為之前「編碼人員能擅自取消儿上聯功能」的做法是錯誤的，儿在任何構字中均有上聯功能，未見不能聯者。你可以把「新官方編碼」稱之為「二〇五」。

我說「允充皃兒」等字是連體字，我並不需要編碼的證明。某些人在得不到編碼證明的情況下，就不知道如何正確的判定結構，那當他們遇到某字的時候您要怎麼辦呢。我正是見某字不吉，因此沒有用，在我所見到的一切儿置底的字，它們都是儿上聯，這裏僅隨手打出幾例而已。儿具有上聯功能是明確寫在倉五手冊的，您不妨回去温習一遍。如果強聯功能也能隨意取消的話，那⺈𠃍偶爾也考慮取消，八ㄦ也根據情況取消，不知道甚麼時候會取消，不知道甚麼時候不取消，戰戰兢兢，如履薄冰，查不到庫典編碼，得不到「官方」肯定，不得安心。

您要不幫「舊官方」「〇三五」解釋一下為甚麼唯獨「兜」儿不上聯，講點道理，不要說官方做的就是對的，沒有道理可言。這個規則要怎麼敍述，怎麼寫進您的維敎裏面去。否則您要寫「我們不知道為甚麼兜儿不上聯，反正〇三五官方查到漢文庫典的編碼是這個」，那用徐碼的都笑得前翻後仰。

您要討論「ㄦ」字，請另開一貼吧，東拉西扯，轉移話題，運用各種技倆字海戰術死纏爛打的人是哪位，各位心中有數。
[end]



我們也沒有道理支持若「儿」不視爲與其上的橫向筆劃相聯就要取「中」不取「竹」。玄學家卻還是沉迷在自己的妄想玄學中。
------
ej:如果您連這個問題都沒搞明白的話，那您可能要再去思考一下。自己再想辦法提髙您的理解能力和認識水平。祝您在閱讀了我的回覆以後有所進步。
[end]

Sent from my Priv+倉頡

**Comment by mrhso** [comment]
仓颉 Project 成员即日起拉黑 E 某。
