### ISSUE TITLE
「𭐦」字取碼

### ISSUE THREAD

**Issue by SyaoranHinata** [Jackchows/Cangjie5#193]
這字目前取YCMHE，似乎視作「𰁜･一･夂」？
好不好兼容「𰁜･⿱一夂」，增YCME此兼容碼？

**Comment by danny0838** [comment]
Unicode code chart 只有一種字形：

![圖片](https://user-images.githubusercontent.com/531417/90326620-0db4ff00-dfbd-11ea-9c8f-e59ad4baac07.png)

IVD 也沒有此字的資料。

**Comment by SyaoranHinata** [comment]
如果只依 Unicode code chart 那字形，好像視作「𰁜･⿱一夂」，取YCME更佳？

**Comment by Jackchows** [comment]
這個「一」和「夂」很明顯是分開的吧。
