### ISSUE TITLE
「𦥆」字取碼

### ISSUE THREAD

**Issue by SyaoranHinata** [Jackchows/Cangjie5#194]
「𦥆」目前取QMNOG，似把上方當成「龶」。
唯「𦥆」之上從「丰」，應改爲QJNOG。

**Comment by danny0838** [comment]
Unicode code chart 有三種字形，可考慮兼容：

![圖片](https://user-images.githubusercontent.com/531417/90723840-0ad54980-e2f0-11ea-8912-138ff883e127.png)
