### ISSUE TITLE
「𩤗」字取碼

### ISSUE THREAD

**Issue by SyaoranHinata** [Jackchows/Cangjie5#195]
「𩤗」字目前取SFBOU，似乎將其右上方當成「祭」之首。
唯此字右上方非「祭」之首，乃「癶」之左併「祭」之右上。故當取SFNOU。

**Comment by danny0838** [comment]
查了 code chart，應該是這樣沒錯。

![圖片](https://user-images.githubusercontent.com/531417/90723926-3a845180-e2f0-11ea-9f50-c00d297f33d3.png)
