### ISSUE TITLE
「𣈩」字取碼

### ISSUE THREAD

**Issue by SyaoranHinata** [Jackchows/Cangjie5#196]
「𣈩」目前取ANOC，疑因取碼字形誤作「⿳日癶𠔁」所致。
按此字《集韻》作「⿳日⿰𠂈(祭之右上)仌」，《康熙》、《漢語大字典》皆作「⿳日⿰癶仌」，
依前者當取AVOO，依後者當取ANOO。

**Comment by Jackchows** [comment]
![圖片](https://user-images.githubusercontent.com/10194519/93009967-8b1e6000-f5b9-11ea-85ea-7873091d4bbc.png)
T源是「𠔁」。
