### ISSUE TITLE
「𫠦」的編碼

### ISSUE THREAD

**Issue by SyaoranHinata** [Jackchows/Cangjie5#2]
不論「一中中弓」還是「一戈中弓」，皆不明字形何據。

此字花園明朝WIKI作此：
http://zhs.glyphwiki.org/wiki/u2b826

似乎宜取「一卜中弓」？

**Comment by Jackchows** [comment]
此字我是這樣拆的：![u 2b826](https://user-images.githubusercontent.com/10194519/27088700-ffa57828-508a-11e7-8352-448800451e9f.png)，因為此字有一異體「![dkw-00052 5 50px 1](https://user-images.githubusercontent.com/10194519/27088831-5b5da5f0-508b-11e7-8915-1442f6b948ce.png)」，因此我認為一點不與左邊的豎相連。

**Comment by SyaoranHinata** [comment]
原來如此，終於明白了。

不過「鸟」字取「心卜尸一」，那個「卜」的豎與點也是不相連啊。看來「豎點」是否相連也可以取「卜」。
