### ISSUE TITLE
三代符號

### ISSUE THREAD

**Issue by cmingwill** [Jackchows/Cangjie5#201]
請問會增加三代倉頡中以ZX為開首的符號嗎？
不少的三代符號五代均未有收錄，例如各種垂直括號「︵︶﹁﹂」與頓號「﹑、」等等。

**Comment by mrhso** [comment]
这不是官方三代的符号。

**Comment by Jackchows** [comment]
可以考慮在[MSCJData](https://github.com/Jackchows/Cangjie5/releases/tag/v1.7.1)中加入微軟倉頡收錄的符號。

**Comment by marriochoose** [comment]
敬請閱讀[《數學家馬拉錘先生的三大功績》](https://github.com/GHolk/cjns/issues/6)

**Comment by pbnec** [comment]
但最近的版本仍未加入，相當可惜。
而其實Android和iOS的倉頡也可輸入ZX為開首的符號，希望補完計劃的開發員能夠加入這些符號，謝謝！

**Comment by Jackchows** [comment]
已在[MSCJData](https://github.com/Jackchows/Cangjie5/releases)中加入微軟倉頡「zx」開頭的標點符號。
RimeData暫不考慮加入，因是「zx」開頭的標點符號不是官方定義的，官方已有「yyy」開頭的標點符號。
