### ISSUE TITLE
「𠫓」

### ISSUE THREAD

**Issue by cmingwill** [Jackchows/Cangjie5#203]
「𠫓」取碼為KI
少數字如「𠭩」「𠘺」則均有取KI-與YI-為首
而「育」「充」「𪺮」「𣏋」等不少以「𠫓」為開首的字卻只有取YI-為首
應新增容錯或是修改嗎？或是有著其他衡量準測？
謝謝～

**Comment by Jackchows** [comment]
暫時按如下規則處理：統一按取「![G](https://user-images.githubusercontent.com/10194519/109407291-97a54200-79ba-11eb-8a08-1d881565b450.png)」形取「YI」，若Unicode [Code Charts](https://unicode.org/charts/)裡祇收錄「![T](https://user-images.githubusercontent.com/10194519/109407305-c9b6a400-79ba-11eb-9d0c-abfd4435a942.png)」字形，則兼容「YI」和「KI」。
