### ISSUE TITLE
「原」不應視為複合字首

### ISSUE THREAD

**Issue by ceku012** [Jackchows/Cangjie5#207]
詳見[維基教科書相關討論](https://zh.wikibooks.org/wiki/Talk:%E5%80%89%E9%A0%A1%E8%BC%B8%E5%85%A5%E6%B3%95/%E4%BE%8B%E5%A4%96%E5%AD%97#%E3%80%8C%E5%8E%9F%E5%8E%A5%E3%80%8D%E5%85%A9%E5%80%8B%E8%A4%87%E5%90%88%E5%AD%97%E9%A6%96%E6%87%89%E4%B8%8B%E6%9E%B6)（口水戰可以略過，主要是最後幾段的相關證據）。

舊版維基教科書把「原」列為複合字首應是來自其他來源，目前已難查證。最近重新調查，三代手冊未把「原」列為複合字首，三代手冊和漢文庫典的「愿」都是「⿱原心」字形，按此字形取碼「一火.心」是合理的。

五代手冊把「原」列為整體字，但此做法明顯違反其他相似字形的取碼慣例（「白」一般不和「厂」、「广」、「𠘨」等字形視為相連，比如「凰」不取作「竹日.一土」），似乎應比照「幽」誤列為整體字的先例視為錯誤。

五代手冊附錄把「愿」寫成「⿸原心」，但並未於三五代改碼表中說過有更改相關規則或取碼字形，如果按照三代、97五代、03五代連貫的預設，似乎應認為倉頡系統取碼所據字形一貫為「⿱原心」，五代手冊字形有誤。

「原」如果視為複合字首，會引來「𠪥」是否也應視為複合字首的爭議，但「𠪥」官方是明確視為分體字、非複合字首，例如「𠫐」的漢文庫典取碼為「一.竹日.水」。按此個人認為「原」也不應該自行視為複合字首。

綜上所述，我認為無論是三代或五代，「原」應視為分體字（「一.竹日火」），且不應視為複合字首。會帶來的問題是相關字「愿」等如果有「⿱原心」、「⿸原心」兩種常見寫法，或許應支援「一火.心」、「一.竹火.心」兩種兼容取碼（相關字目前有查到：𧏐、𧔞）。

**Comment by cccjjjcjcj92** [comment]
怎麼沒人回覆呢？到底有沒有人同意ceku的觀點？？？

**Comment by Jackchows** [comment]
暫不考慮修改。
