### ISSUE TITLE
「𠄣」

### ISSUE THREAD

**Issue by SyaoranHinata** [Jackchows/Cangjie5#216]
今取MBHM，可疑。
似乎應取MNHM。（全取作MNHHM，整體字只取首次三尾，故爲MNHM。）

**Comment by SyaoranHinata** [comment]
「𣍭」
今取BMBM。
似乎應取BMNM。

**Comment by Jackchows** [comment]
似乎MBHM和MNHM均可接受，[庫典](http://chidic.eduhk.hk/v.php?id=71239)取了MBHM，暫且跟從庫典。
