### ISSUE TITLE
麥字邊取碼

### ISSUE THREAD

**Issue by TNTErick** [Jackchows/Cangjie5#218]
不知有無人提過了，但
使用倉頡平台2022的五倉世紀時我注意到了麥作字首時有時取作十水、有時取木水。

**Comment by Jackchows** [comment]
本項目的麥字邊是兼容「十水」和「木水」的，如發現有遺漏請回報，以便修改。
「倉頡平台2022」只有Unicode CJK擴展區C-G使用本項目碼表，其餘部分仍是使用原有碼表。
