### ISSUE TITLE
看不見的字

### ISSUE THREAD

**Issue by kentsin** [Jackchows/Cangjie5#231]

**Comment by kentsin** [comment]
碼表中有很多字看不見的

是否可以將碼表拆細。 容許用戶組合生成碼表， 一來少了看不見的字會加快輸入法的速度， 最重要是減少重碼和錯選

**Comment by JLHwung** [comment]
可以使用特別版本Cangjie5_Special.txt，這裡收錄的都是常見字和今天的操作系統應該都能顯示的字。
