### ISSUE TITLE
Windows 碼表裡的 永, 浆 兩個字

### ISSUE THREAD

**Issue by charlesnieh** [Jackchows/Cangjie5#235]
看了原始碼表, 永是 ine, 浆是 lne, 明顯不同, 但在 windows 上輸入 ine 浆會跑出來, 而且還排在永之前. 請問是 windows 輸入法引擎的問題嗎?

**Comment by Jackchows** [comment]
Windows 10/11有方法替換微軟倉頡的碼表，見[這裡](https://github.com/Jackchows/Cangjie5/releases)。

**Comment by charlesnieh** [comment]
事後發現這個錯誤是因為電腦在 Windows 10 升級 Windows 11 後，系統自動回復原來的碼表。

而我在 Windows 11 中 “再次" 替換碼表時，忘記像 Windows 10 裡一樣刪掉該刪的檔案造成的。不好意思麻煩您了。
