### ISSUE TITLE
Ext A 中 20 字修改

### ISSUE THREAD

**Issue by pttp** [Jackchows/Cangjie5#24]
㐒  srn -> shrn 
㐄  jv -> ql 
㐓  mnrn -> mrn 
㐦  hqn -> hcqn 
㐬  yihu -> yihlu 
㐷  onvm -> osm 
㒊  osim -> oshm 
㒏  ojty -> ojtm 
㒹  jcjbc -> jcjuc 
㔟  hiks -> hkks 
㕓  mwfg -> mwgg 
㖄  rill -> rhll 
㖖  ytjr -> yjr 
㘸  mnpg -> mpg 
㙌  glx -> glll 
㙳  gihp -> girp 
㙶  yrfbg -> yrfg 
㛨  vtgu -> vtqu 
㛳  yblbv -> ybv 
㜅  vyiw -> vyvw 

根据官方取码资料，这些字要修改

**Comment by Jackchows** [comment]
**㐒 srn -> shrn**
同意修改。
**㐄 jv -> ql**
同意修改。
**㐓 mnrn -> mrn**
同意修改。
**㐦 hqn -> hcqn**
同意修改。
**㐬 yihu -> yihlu**
同意修改。
**㐷 onvm -> osm**
『「马」減去「一」』是〇三五代新增的輔助字形。本項目主要依九九五代取碼，未採納此修改。
**㒊 osim -> oshm**
字形兼容。
**㒏 ojty -> ojtm**
字形兼容。
**㒹 jcjbc -> jcjuc**
字形兼容。
**㔟 hiks -> hkks**
「倉頡之友·馬來西亞」在「丸」的取碼上有問題，將統一修改。
**㕓 mwfg -> mwgg**
同意修改。
**㖄 rill -> rhll**
字形兼容。
**㖖 ytjr -> yjr**
同意修改。
**㘸 mnpg -> mpg**
同意修改。
**㙌 glx -> glll**
同意修改。
**㙳 gihp -> girp**
同意修改。
**㙶 yrfbg -> yrfg**
同意修改。
**㛨 vtgu -> vtqu**
字形兼容。
**㛳 yblbv -> ybv**
[說明](https://github.com/Jackchows/Cangjie5/blob/master/change_summary.md)中已解釋。
**㜅 vyiw -> vyvw**
同意修改。

**Comment by SyaoranHinata** [comment]
㐄 jv -> ql
這個字有兩個字形。
一個是「年的下方」，取QL合理。
另一個是「舛的右旁」，三筆，宜取QV。

**Comment by Jackchows** [comment]
同意修改。
