### ISSUE TITLE
講道理才是唯一出路

### ISSUE THREAD

**Issue by zuzuzulie** [Jackchows/Cangjie5#241]
# 講道理才是唯一出路
2022-03-03 by [ejsoon](https://ejsoon.win/author/ejsoon/)

希望 ichirou 能夠重新回到談判桌上来，只有講道理才是唯一出路。對我誣衊構陷、人身攻擊、刪帖封號，不能提升維基倉教的質量，也不能提高ichirou等人的倉頡規則敍述水平。

維基倉教是騎沈四傑的原創理論投放地，裏面包含了大量錯誤荒謬可笑的個人理論。例如「舊體字字元、骨頭字元—咼商一致論、外圍繁複論、懬垕結構判定不清不楚、書法結字、三死首、五隱首、取碼原則優先級、區塊原則」等等。

前面已經有不少錯誤的內容因被狙擊而下架，比如「春冬登大翻車、剪刀原則、西字、原字、班辨平頭」等。如果維基倉教寫的甚麼都對，那麼維基倉教根本不必承認任何錯誤，也不必下架任何內容。

我曾向兩位前輩請教，一位是八十年代參與中文之星開發的資深老者，另一位就是年逾七十仍不遺餘力推廣倉頡的謝孟振前輩。

當我問兩個前輩「咼是連體還是分體」時，都得到明確的答覆，他們都說「咼」是分體字。有截圖和錄音為證。

如果ichirou跟馬拉錘，懂的尊重前輩，他們就應該直接問「三五代倉頡有沒有骨頭字元」，「咼是不是連體」，而不是耍小聰明，運用語言技巧，騎劫沈紅蓮。

ichirou跟馬拉錘自己作了個可笑的推論，以為「卨」字編碼為理由，之後再把沈紅蓮安排在他們的推論中的一環。這其實是對前輩最大的不敬。

沈紅蓮的回覆裏，根本沒有同意「卨是連體字」，他也沒有清晰的講「三代如何、五代如何、〇三五如何、六代如何」，他根本沒有注意到第二問偷偷的切換了倉頡版本。

現在你們騎沈的整個過程已經被曝光，被評論。ichirou越是講有「官方依據」，大家越能看清他們的行為。

希望你們停止上架個人原創的錯誤理論，停止對他人進行誹謗攻擊。因為你們現在沒有掌握軍隊和警察，你們的「權力」只限於fb群組、大馬倉友管理權，因此你們根本做不到對信息的完全封鎖，刪帖封號刪不盡封不完，春風吹又生。

在這個信息時代，一個人如果不講道理，單純想靠誹謗他人来生存，那真的是太難了。騎沈四傑的理論實在過於幼稚，下架之後自己都不忍再提（比如無敵公式、剪刀原則等）。

希望ichirou等人回到講道理的談判桌上，現在的普世價值是言論自由，有理走遍天下，無理寸步難行。

你們的理論是錯誤的，是不可理解和應用的，因此一定不會得到人民的支持，公道自在人心，錯誤的規則絕不可能經受住歷史的檢驗！

**Comment by mrhso** [comment]
![BF46E 0D0}(~YAEF@I`_Z`0](https://user-images.githubusercontent.com/13294467/157022636-2e6b23e5-71cb-44c3-beb1-cbe1994c97a0.png)
