### ISSUE TITLE
「𢡍」

### ISSUE THREAD

**Issue by SyaoranHinata** [Jackchows/Cangjie5#251]
目前爲PMBL，不確
應改作PMRB。

**Comment by JLHwung** [comment]
`PMBL` 對應的是 Unicode 5.1 及之前的字形, 即 https://dict.variants.moe.edu.tw/variants/rbt/word_attribute.rbt?educode=C03917-003 也是目前 TWSung-Ext-B 字體中 U+2284D 的對應字形。

Unicode 6.0 之後這個字形變成了 ⿰忄鬲，所以應改爲 `PMRB`。原來`PMBL`可以作爲兼容性處理，作`[U]`標記，不必刪除。該問題已經在 https://github.com/JLHwung/Cangjie5 得到修復，未來會 PR 到此倉庫。

**Comment by SyaoranHinata** [comment]
舊版字形是指「![image](https://user-images.githubusercontent.com/8178284/196057210-4bbbe347-7958-47fb-91ea-96b29f1e768e.png)」嗎？但這取碼也有問題。
像「髙」是取YSLB，視爲整體字的。不取「YB.R」。
同理，「![image](https://user-images.githubusercontent.com/8178284/196057180-51fdbe96-10d2-4a60-b93c-7a3f5b6fb3c8.png)」也應視爲整體字，取MSLB。
因此，「![image](https://user-images.githubusercontent.com/8178284/196057214-63e0a147-cc75-4bf3-9f7f-1588cd609c20.png)」應取「P.MSB」，而不是現在的「P.MB.L」。
