### ISSUE TITLE
「𩍫」

### ISSUE THREAD

**Issue by larachung** [Jackchows/Cangjie5#254]
<img width="211" alt="image" src="https://user-images.githubusercontent.com/103840434/177315828-f8c45507-40f6-4cff-8783-fec349fa834d.png">
「𩍫」在 Unicode 中有兩種字形，分別是從「土」與從「⿰丨二」，目前表中的「𩍫」字有 TJBGE（舊 T 源）和 TJLUE（其他）兩種取碼，前者對應了從土的字形，但後者並不對應從⿰丨二的字形，是否應將 TJLUE 更改為 TJBLE 以對應正確的字形？

**Comment by Jackchows** [comment]
個人傾向不保留舊版本字形，故：
TJBGE改為TJBLE
TJLUE刪去
