### ISSUE TITLE
「𪬪」

### ISSUE THREAD

**Issue by Hulenkius** [Jackchows/Cangjie5#257]
誤：olonp
正：olomp

**下邊兒楊師已經給了他的答案，請參考他的。**

**Comment by Arthurmcarthur** [comment]
我認為「个」應該和「介」一樣屬於組合字。參考「𠁭」取碼「人.中.人中」、「𠌕」取碼「人.中中.中」、「㖋」取碼「人.中中.心」，本字取碼「人.中.人心」較恰當。
