### ISSUE TITLE
𩰲部

### ISSUE THREAD

**Issue by frstyl** [Jackchows/Cangjie5#269]
𩰲部44字全褈碼。𩰲部應認爲⿶結構，𩰲爲一體。例如鬻=𩰲（弓月）+米（火木），䰞=𩰲（弓月）+蔑（廿中戈）

鬻	nnmrb
䰞	nnmrb
𩰲	nnmrb
𩱆	nnmrb
𩱌	nnmrb
𩱍	nnmrb
𩱎	nnmrb
𩱓	nnmrb
𩱖	nnmrb
𩱗	nnmrb
𩱚	nnmrb
𩱜	nnmrb
𩱞	nnmrb
𩱟	nnmrb
𩱡	nnmrb
𩱣	nnmrb
𩱤	nnmrb
𩱥	nnmrb
𩱦	nnmrb
𩱧	nnmrb
𩱨	nnmrb
𩱪	nnmrb
𩱫	nnmrb
𩱭	nnmrb
𩱮	nnmrb
𩱯	nnmrb
𩱰	nnmrb
𩱱	nnmrb
𩱲	nnmrb
𩱳	nnmrb
𩱶	nnmrb
𩱷	nnmrb
𫙆	nnmrb
𫙇	nnmrb
𬴸	nnmrb
𬴹	nnmrb
𬴺	nnmrb
𬴻	nnmrb
𬴼	nnmrb
𱆐	nnmrb
𱆑	nnmrb
𱆒	nnmrb
𱆔	nnmrb
𱆕	nnmrb

**Comment by Arthurmcarthur** [comment]
請看本項目的README。
本項目(✓)意圖　修改字碼以貼近官方資料

因此為了減少重碼而修改規則不是本項目的任務。

作者另有一項目：
https://github.com/Jackchows/Cangjie_DIY

6.增設複合字「𩰲(弓片)」
本碼表将「𩰲」列為複合字，取碼「弓片」。「鬻䰞𩱆」等字，以「𩰲」為字首，餘下部份為字身。如「鬻」取碼「弓片火木」
原編碼「弓弓一口月」仍可用。
官方無此複合字。

不過該項目目前處於擱置狀態。

**Comment by Jackchows** [comment]
如Arthurmcarthur所言，這些字按規則是取「nnmrb」。
有需要的話自己加一下即可。

**Comment by SyaoranHinata** [comment]
試試編一編，看看有沒問題

鬻 nzfd
䰞 nzjka
𩰲 nz
𩱆 nzv
𩱌 nzyg
𩱍 nzjr
𩱎 nzlln
𩱓 nzsj
𩱖 nzdl
𩱗 nzmcw
𩱚 nzjbd
𩱜 nzmmv
𩱞 nzjkd
𩱟 nzowy
𩱡 nzoru
𩱣 nzeln
𩱤 nznkq
𩱥 nziim
𩱦 nzpuu
𩱧 nztgf
𩱨 nzmvi
𩱪 nzbmb
𩱫 nzydl
𩱭 nzcwa
𩱮 nzesd
𩱯 nzfdu
𩱰 nzjae
𩱱 nzoyu
𩱲 nzsmg
𩱳 nzyx
𩱶 nzmbg
𩱷 nzfdi
𫙆 nzodi
𫙇 nzimm
𬴸 nzgmj
𬴹 nzbd
𬴺 nzfdu
𬴻 nzfdd
𬴼 nzanp
𱆐 nzgi
𱆑 nzmkk
𱆒 nzihr
𱆔 nzhoo
𱆕 nztwi

**Comment by Jackchows** [comment]
> 試試編一編，看看有沒問題

這幾個

𱆕 nztwi -> nztwh
𫙇 nzimm -> nzimg 
𬴼 nzanp -> nzagp

**Comment by SyaoranHinata** [comment]
謝謝，𱆕、𬴼改好了，之前莫明地錯。

𫙇我有點懷疑，它的內部是「冫隹冫」，所以我取im.ogm→imm，不知大家怎麼看。

**Comment by Jackchows** [comment]
𫙇nzimm是對的，我看錯了。
