### ISSUE TITLE
唱歌！

### ISSUE THREAD

**Issue by Arthurmcarthur** [Jackchows/Cangjie5#270]
It's nine o'clock on a Saturday
The regular crowd shuffles in
There's an old man sittin' next to me
Makin' love to his tonic and gin
He says, "Son can you play me a memory?
I'm not really sure how it goes
But it's sad and it's sweet and I knew it complete
When I wore a younger man's clothes"
La, la-la, di-di-da
La-la di-di-da da-dum
Sing us a song, you're the piano man
Sing us a song tonight
Well, we're all in the mood for a melody
And you've got us feelin' alright
Now John at the bar is a friend of mine
He gets me my drinks for free
And he's quick with a joke, or to light up your smoke
But there's some place that he'd rather be
He says, "Bill, I believe this is killing me"
As a smile ran away from his face
"Well, I'm sure that I could be a movie star
If I could get out of this place"
Oh, la, la-la, di-di-da
La-la di-di-da da-dum

**Comment by Jackchows** [comment]
Nice song
