### ISSUE TITLE
「麦」

### ISSUE THREAD

**Issue by pea-snow** [Jackchows/Cangjie5#272]
字元「麦」的取碼（手大水）錯誤
事實上，上方的「龶」與下方的「夂」並未相連，Gboard中的倉頡五代因此將其取碼為「手一竹水」
![Uploading 麦 - sample.png…]()

**Comment by JLHwung** [comment]
官方取碼`QME`：http://chidic.eduhk.hk/v.php?dicword=%E9%BA%A6 本項目已收錄。

<img width="461" alt="image" src="https://github.com/Jackchows/Cangjie5/assets/3607926/809f3985-3ebc-4ba0-b815-5cd300483197">

在該字元的J字形中，上方的「龶」與下方的「夂」是相連的。但對於其他地區不相連的字形，Gboard的`QMHE`我覺得還不錯，或許可以添加。

**Comment by jyk0201** [comment]
这边大麦bp可长期提供，有需要的来➕q2814249606，标明github

**Comment by 18303060635** [comment]
2814249606跑路狗 别上当

**Comment by Jackchows** [comment]
官方取碼是[`QME`](http://chidic.eduhk.hk/v.php?id=46465)和[`QKE`](http://chidic.eduhk.hk/v.php?id=46245)。
因為「唛」「𨀱」等字有`QKE`的字形，故「麦」也保留`QKE`以保持一致。
![圖片](https://github.com/Jackchows/Cangjie5/assets/10194519/5f512477-2f43-430e-8c57-c295020a98f6)
![圖片](https://github.com/Jackchows/Cangjie5/assets/10194519/0251d5a1-f1f9-413c-b4a0-106a9988cf69)
