### ISSUE TITLE
Unicode 15.1 新增 IDC 字符建議取碼

### ISSUE THREAD

**Issue by JLHwung** [Jackchows/Cangjie5#274]
Unicode 15.1 新增表意文字描述符號五個，建議取碼如下：

```
⿼	ziws
⿽	ziwlm
⿾	ziwm
⿿	ziwk
㇯	ziwa
```

其中⿾也可取zia, 但wm可以和已有的⿱區分，後面的m視作mirror縮寫也方便記憶；⿿則遵循已有的彎曲部件取「大」的決定。

**Comment by Jackchows** [comment]
我覺得⿾也可取ziwvm，⿿也可取ziwz（本項目原有用z表示旋轉的規則）。
不過將IDC當作漢字本來就很怪，加兩個兼容碼得了，不用太講究。XD

**Comment by JLHwung** [comment]
> 我覺得⿾也可取ziwvm，⿿也可取ziwz（本項目原有用z表示旋轉的規則）。

您這個提議不錯，就按您說的規則取碼吧，我覺得可以不用兼容了，除非別人也支持我的提議。

我在IRG工作中經常要使用到IDS，本輸入方案包括了IDC字符，着實方便不少。我以爲當漢字只是方便記住鍵位，不然像普通符號一樣需要挨個查找，容易出錯。
