### ISSUE TITLE
打包錯誤

### ISSUE THREAD

**Issue by pea-snow** [Jackchows/Cangjie5#278]
在目前版本（v3.1）中，一般排序的輸入法配置檔實際上無任何內容，其他排序正常
疑為打包發布時出現錯誤所致
![image](https://github.com/Jackchows/Cangjie5/assets/69971066/5e62d4f7-cde1-4704-9eda-ebf2178c31a8)

**Comment by Jackchows** [comment]
已替換，感謝提醒。
