### ISSUE TITLE
 『己經』的正式字形是『已經』

### ISSUE THREAD

**Issue by Meavel** [Jackchows/Cangjie5#279]
你好，這裡提交一個issue，在最新版的碼表中，輸入『已經』這個詞，即，輸入：尸山一火一女一，出現的是『己經』，這或許是詞庫的問題。

**Comment by Jackchows** [comment]
你好，這個碼表是單字碼表，不包含詞庫。輸入「尸山女火一女一」出現「己經」是輸入法軟件的功能，不受碼表控制。

如果你使用的是RIME系列輸入法（例如小狼毫），可以在`cangjie5.custom.yaml`裡配置開啟用戶詞典功能：
```
patch:
  translator/enable_user_dict: true
```
這樣，在輸入過一次「已經」之後，會自動記錄這個詞。不過，開啟用戶詞典功能後，候選字（包括單字）排序將不再是固定的。
