### ISSUE TITLE
「𠀫𠀪」不統一

### ISSUE THREAD

**Issue by SyaoranHinata** [Jackchows/Cangjie5#280]
其，官方取TMMC，下方的「ハ」視爲與上方相連，依整體字的規則取碼。本計劃依之。

𠀫，官方取TMH，按此應視爲組合字。本計劃依之。

𠀪，一時間未尋得官方取碼。本計劃取TMMI，似與「其」看齊。但字形劃分的規則中，「ハ」的確視爲與上方相連，單獨一點卻似乎不然。
大概「𠀪」與「𠀫」看齊，取TMI爲佳？

**Comment by Jackchows** [comment]
「𠀪」取TMMI是考慮到「丶」附屬於整個字形視為整體字的規則。

**Comment by Jackchows** [comment]
加了容錯。
