### ISSUE TITLE
「𢎘」

### ISSUE THREAD

**Issue by SyaoranHinata** [Jackchows/Cangjie5#281]
𢎘，今取SVS。
宜增NVS兼容第一筆不帶鈎之字形。

**Comment by Jackchows** [comment]
T源在Unicode 6.0就改字形了（圖一），現行的GB18030-2022（圖二）和CNS11643（圖三）也不是NVS的字形，我覺得可以不加。
![圖片](https://github.com/Jackchows/Cangjie5/assets/10194519/6d120fba-896c-465b-b1d1-ab8dd8ebf671)
![圖片](https://github.com/Jackchows/Cangjie5/assets/10194519/c2e953c9-0c31-4403-a73c-3c2414c68826)
![圖片](https://github.com/Jackchows/Cangjie5/assets/10194519/09a04a03-9b17-453d-968e-d73798eb62ea)

**Comment by Jackchows** [comment]
暫未修改。
