### ISSUE TITLE
疑似錯誤編碼

### ISSUE THREAD

**Issue by eps271828** [Jackchows/Cangjie5#294]
𤴛、𤭑  二字疑似編碼錯誤，前者按常理應取“jiyo十戈卜人”或“jwio十田戈人”，却取了“hwio竹田戈人“，後者按常理應取“mrmvn一口一女弓”却取了“mmmvn一一一女弓”
![螢幕擷取畫面 2024-07-25 090520‘](https://github.com/user-attachments/assets/ea9af559-3df3-40cc-9241-ba98a8645374)
![螢幕擷取畫面 2024-07-25 090500](https://github.com/user-attachments/assets/198244f1-8299-4762-ab15-b3e64a287f53)

**Comment by eps271828** [comment]
windows11,小狼毫平臺，五代（繁）補全碼表

**Comment by Jackchows** [comment]
是錯了，稍後改。
