### ISSUE TITLE
「⿱八一」頭取碼

### ISSUE THREAD

**Issue by SyaoranHinata** [Jackchows/Cangjie5#35]
不少新字形作「䒑」頭的字，傳承字形是「⿱八一」頭。目前的「主要改碼說明及爭議取碼」說明中，只列出「益」字作例子。會否增加在碼表上已支援的「酋」等例子？

另外，目前碼表上尚未支援「⿱八一」頭的字，如「曾」，日後會否支援？

**Comment by Jackchows** [comment]
「說明」中有列出「酋」。
會支援「⿱八一」，但因為較難篩選出所有含「⿱八一」的字批量修改，所以目前是按較大的部件（如「益」、「酋」）分批修改。
