### ISSUE TITLE
「乜、忆」宜調轉次序

### ISSUE THREAD

**Issue by SyaoranHinata** [Jackchows/Cangjie5#39]
目前「先忆後乜」
「乜」字是繁體字暨傳統字，在北方地區未必常用，但在南方地區極常用。
「忆」字是簡化字。
宜先繁後簡。

**Comment by Jackchows** [comment]
「乜」另有「ps」一碼，「ps」沒有重碼字。我覺得「pn」讓給「忆」可能更合適。

**Comment by SyaoranHinata** [comment]
這樣的話，「也」會不會支援「PJS」作異體碼？

**Comment by Jackchows** [comment]
會考慮。
