### ISSUE TITLE
「踭」宜增異體碼

### ISSUE THREAD

**Issue by SyaoranHinata** [Jackchows/Cangjie5#41]
目前「踭」只能以「口一弓尸木2」輸入，即「⿰𧾷争」形。
但Unicode把「⿰𧾷争」形與「⿰𧾷爭」形都統合在此字碼中，
而這字是香港常用字，香港人都寫「⿰𧾷爭」形。故宜增「口一月尸木」。

**Comment by Jackchows** [comment]
同意增加「口一月尸木」。
