### ISSUE TITLE
「𠤛」的取碼

### ISSUE THREAD

**Issue by SyaoranHinata** [Jackchows/Cangjie5#42]
「𠤛」目前取「心中尸中」，按在下之前說的[三、五代高低取法差異](https://github.com/Jackchows/Cangjie5/issues/17#issuecomment-365384307)，這其實是三代取法。
按五代取法，則應是「心中中中」。
而漢文庫典正是五代取法：http://hanculture.com/dic/v.php?id=45052
建議增加兼容碼。

**Comment by Jackchows** [comment]
已修改。
