### ISSUE TITLE
「黃」部件取碼

### ISSUE THREAD

**Issue by SyaoranHinata** [Jackchows/Cangjie5#45]
「黃」形取「廿一中金」，「黄」形取「廿中田金」。甚是。

唯從此偏旁者，如「熿、璜、潢、撗、獚、磺、穔、蟥、觵、鐄、鱑、黋」等，只支援「廿中金」，不支援「廿一金」，非是。

宜兼容之。

**Comment by Jackchows** [comment]
已完成。（版本 [f7a728e](https://github.com/Jackchows/Cangjie5/commit/f7a728edfb2e21e80f0168ccda70bd3ebb4a8b3c)）
