### ISSUE TITLE
「旨、旬」宜調轉次序

### ISSUE THREAD

**Issue by SyaoranHinata** [Jackchows/Cangjie5#46]
今「先旬後旨」。
「旨」比「旬」常用。
宜調之。

（但「詢、詣」「指、㧦」排序OK，不用調。）

**Comment by Jackchows** [comment]
查了
[《國語辭典簡編本編輯資料字詞頻統計報告》](http://language.moe.gov.tw/001/Upload/files/SITE_CONTENT/M0001/PIN/c11.htm?open)：兩字頻率相同，均為0.002%。
[《常用字頻序表》](http://humanum.arts.cuhk.edu.hk/Lexis/lexi-can/faq.php)：「旬」頻次488，列1885位；「旨」頻次449，列1934位。
北京语言大学汉语国际教育技术研发中心《汉字字频表》（下載連接已失效）：「旬」頻次510，列3200位；「旨」頻次1091，列2682位。
百度搜索：[「旬」](https://www.baidu.com/s?wd=%22%E6%97%AC%22)結果42,200,000項，[「旨」](https://www.baidu.com/s?wd=%22%E6%97%A8%22)結果100,000,000項。
Google.hk搜索：[「旬」](https://www.google.com.hk/search?q=%22%E6%97%AC%22)結果199,000,000項，[「旨」](https://www.google.com.hk/search?q=%22%E6%97%A8%22)結果143,000,000項。

似乎不能分出高下？

**Comment by SyaoranHinata** [comment]
[香港、大陸、台灣 — 跨地區、跨年代漢語常用字頻統計](http://humanum.arts.cuhk.edu.hk/Lexis/chifreq/)

六十年代香港：
旨　1804
旬　2727

八、九十年代香港：
旨　2009
旬　2507

六十年代台灣：
旨　1960
旬　2385

八、九十年代台灣：
旨　2190
旬　3456

六十年代大陸：
旬　1967
旨　2313

八、九十年代大陸：
旨　1980
旬　2710

旨：旬　爲　5：1

**Comment by Jackchows** [comment]
我覺得這資料比較舊，未必能反映當前情況。

**Comment by Jackchows** [comment]
未修改。
