### ISSUE TITLE
「冊、皿」次序宜調轉

### ISSUE THREAD

**Issue by SyaoranHinata** [Jackchows/Cangjie5#47]
目前「先皿後冊」。
「冊」比「皿」常用。

**Comment by SyaoranHinata** [comment]
[香港、大陸、台灣 — 跨地區、跨年代漢語常用字頻統計](http://humanum.arts.cuhk.edu.hk/Lexis/chifreq/)

六十年代香港：
冊　1962
皿　4061

八、九十年代香港：
冊　1470
皿　1950

六十年代台灣：
冊　1681
皿　2071

八、九十年代台灣：
冊　1734
皿　榜外

六十年代大陸：
冊　2058
皿　3254

八、九十年代大陸：
冊　2028
皿　4520

冊：皿　爲　6：0

**Comment by Jackchows** [comment]
已在[17bd086](https://github.com/Jackchows/Cangjie5/commit/17bd086f5f057cb52a0a4fd1a8dc2842ca4d31c2)修改。
