### ISSUE TITLE
「𧾷」的取碼

### ISSUE THREAD

**Issue by SyaoranHinata** [Jackchows/Cangjie5#51]
今取「口卜女」，誤。應取「口卜中一」。
http://hanculture.com/dic/v.php?id=49896

倉頡不計算書法裝字，即末橫變挑，仍算作橫。
像「𤴔」取「弓卜中一」而非「弓中女」。
http://hanculture.com/dic/v.php?id=39150

**Comment by Jackchows** [comment]
已修改，累積一定數量修改後發佈。
