### ISSUE TITLE
「斉」的取碼

### ISSUE THREAD

**Issue by SyaoranHinata** [Jackchows/Cangjie5#52]
目前取「卜大尸中」。但「丿二」算「尸」嗎？
「卜大中中一」或「卜大中一中」又如何呢？

**Comment by SyaoranHinata** [comment]
「漢文庫典」是「卜大中」，這碼十分非常極之有可疑……
http://hanculture.com/dic/v.php?dicword=斉

對我來說，似乎應拆「卜大.卜人中」（亠乂.⺊𠂉丨）比較妥當，
或者特別說明「丿二」和「ㅑ」也一樣是「尸」的輔根。

**Comment by Jackchows** [comment]
我認為「丿二」中的「丿」，屬於「儿」一類遷就書寫作出的形變，可以按「丨」取，故可取「尸」。

**Comment by SyaoranHinata** [comment]
我也有這樣想過，若是這樣做的話建議加入說明。

**Comment by Jackchows** [comment]
已添加說明。（版本 [f7a728e](https://github.com/Jackchows/Cangjie5/commit/f7a728edfb2e21e80f0168ccda70bd3ebb4a8b3c)）
