### ISSUE TITLE
「宀禸」宜調轉次序

### ISSUE THREAD

**Issue by SyaoranHinata** [Jackchows/Cangjie5#53]
都不是常用字，通常是說部件時提及它們。
但「宀」部件比「禸」部件常用得多，常常提及。
「禸」部件則十年不逢一潤。

**Comment by Jackchows** [comment]
「禸」列於《次常用國字標準字體表》，「宀」非。
一般排序、簡化字優先版本修改排序為「宀、禸」，傳統漢字優先版本維持「禸、宀」。（版本 [f7a728e](https://github.com/Jackchows/Cangjie5/commit/f7a728edfb2e21e80f0168ccda70bd3ebb4a8b3c)）
