### ISSUE TITLE
「丞、亟」宜調轉次序

### ISSUE THREAD

**Issue by SyaoranHinata** [Jackchows/Cangjie5#54]
目前「弓水一」是「先亟後丞」。
但「丞」比「亟」常用，此其一。
「亟」一般取「一水一」，「弓水一」只是兼容碼，「丞」卻只能取「弓水一」，此其二。
故宜調轉之。

**Comment by Jackchows** [comment]
一般排序、傳統漢字優先版本已修改排序為「丞、亟」，簡化字優先版本維持「亟、丞」。（版本 [f7a728e](https://github.com/Jackchows/Cangjie5/commit/f7a728edfb2e21e80f0168ccda70bd3ebb4a8b3c)）
