### ISSUE TITLE
「憲」字取碼

### ISSUE THREAD

**Issue by SyaoranHinata** [Jackchows/Cangjie5#55]
「害」有「十手十口」、「十手一口」兩種寫法的取碼
但「憲」字只有「十手一心」一種，未支援「十手十心」的寫法。
「𡩐、𡩜」二字也只有「十手一田」，未有「十手十田」。
「𧒡」字則相反，只有「十手十戈」，未有「十手一戈」。
建議都支援。

**Comment by Jackchows** [comment]
已修改。
