### ISSUE TITLE
「丟」的次序

### ISSUE THREAD

**Issue by SyaoranHinata** [Jackchows/Cangjie5#56]
目前「一土戈」的次序是：1.玉 2.压 3.丟 4.玊 5.㺨 6.𠩂

「丟」比「压」常用 （剛剛才知「压」字，平時確實沒爲意）
宜 2.丟 3.压 。

**Comment by Jackchows** [comment]
傳統漢字版本是：1.玉 2.丟 3.玊 4.压，已是先「丟」後「压」。
一般排序版本是：1.玉 2.压 3.丟 4玊，因綜合考慮繁簡體，「压」比「丟」常用。（且與「丟」相比，「丢」更常用。）

**Comment by SyaoranHinata** [comment]
其實繁體字中是多用「丟」少用「丢」的。
只是以前在Big-5環境，因異體編碼問題，大家習慣打「竹土戈」出「丟」字而已。

**Comment by Jackchows** [comment]
我的想法是這樣：
傳統漢字優先版本針對主要使用繁體，甚少使用簡體的人士。
一般排序版本針對同時使用繁體和簡體的人士，因此會避免常用的簡體字排得太後。若兼顧繁簡體，「压」比「丟」常用。

**Comment by Jackchows** [comment]
未修改。
