### ISSUE TITLE
增加使用許可（License）

### ISSUE THREAD

**Issue by SiuMing127** [Jackchows/Cangjie5#58]
大家好，我不是來提出與倉頡碼有關的問題……
我希望在自己的專案上使用這個碼表，故希望 @Jackchows / @mrhso 或其他貢獻者能為此 Repository 增加使用許可（License），例如 MIT / CC-BY 4.0 等。
謝謝

**Comment by Jackchows** [comment]
這份碼表是基於「倉頡之友·馬來西亞」論壇「倉頡平台 2012」軟件中的碼表進行修改。Unicode CJK 基本區至擴展D區的部份來自「倉·馬」，擴展E區和擴展F區則主要由我編寫。
我諮詢過「倉·馬」論壇的站長，他的回覆是：「倉頡平台 2012」的碼表有一部分由朱邦復工作室提供，他和論壇網友對碼表進行了校修和擴編，但具體有哪些人參與已無法考據。但他認為該碼表允許任何人無償使用。
先前我亦問過朱邦復工作室的沈紅蓮女士，她說她本人沒有參與過「倉·馬」論壇的編碼工作。（但不能確認朱邦復工作室有沒有向「倉·馬」論壇提供過碼表。）
至於倉頡輸入法本身，發明人朱邦復先生已放棄專利。

以上是本專案的碼表來源。對於不是我本人編寫的部份，我不能確定本人是否有權添加 License。不知道閣下能否就本專案的 License 問題提供建議？謝謝

**Comment by SyaoranHinata** [comment]
記憶中很久以前問過倉頡之友處理的人，說標明他們就可以。用 CC BY、CC BY-NC 條款都可以會 
當然，他們歡迎捐款。（不過現在找人都空谷投音沒人回，恐怕要捐款都沒有人收了。）

後來也問過法律顧問。基本上碼表是誰也能寫出編出的東西，
要是該輸入法沒有註冊，那麼你自己寫碼表也不成問題。
而倉頡的發明人朱邦復先生已說明放棄一切版權/著作權，倉頡即已進入公有領域。

那麼，如果是純自己打出來的碼表，用 PD 都可以吧。
如果經過倉頡之友，就標明取自倉頡之友，然後用任何包含 BY 的 CC 都沒問題的。

**Comment by SiuMing127** [comment]
基於你們的回覆，和我在http://www.chinesecj.com/forum/forum.php?mod=viewthread&tid=5137找到「倉頡之友·馬來西亞」，我同意可以 CC BY 或 CC BY-NC 處理。

**Comment by SyaoranHinata** [comment]
上方我應說「要是該輸入法沒有註冊專利」才對。漏了「專利」二字，特此更正。

**Comment by Jackchows** [comment]
和 @mrhso 、 @Arthurmcarthur 討論後，決定使用[MIT](https://github.com/Jackchows/Cangjie5/blob/master/LICENSE)許可。
