### ISSUE TITLE
「冗」的取碼

### ISSUE THREAD

**Issue by SyaoranHinata** [Jackchows/Cangjie5#65]
「宂」支援「十竹山」和「十竹弓」，
但「冗」今只有「月竹弓」，且與「肌」重碼，宜增「月竹山」。

**Comment by Jackchows** [comment]
似乎找不到「冗」有「月竹山」這種字形。

**Comment by SyaoranHinata** [comment]
不少傳承字形會這樣寫。
另外，香港敎育參考也是這樣寫的啊，本字作「宂」異體作「冗」，下方作「儿」。

**Comment by Jackchows** [comment]
我確實沒有找到「冗」有下方寫作「儿」的，不知一郎兄能否提供一些「冗」下方作「儿」的實際用例？
另外，「香港敎育參考」是指甚麼？

**Comment by SyaoranHinata** [comment]
[img]https://i.imgur.com/y1rSewF.png[/img]

**Comment by Jackchows** [comment]
已修改。
