### ISSUE TITLE
「⺡」和「⻍」取「ZRIY」？

### ISSUE THREAD

**Issue by SyaoranHinata** [Jackchows/Cangjie5#69]
目前變形部首「⺡」和「⻍」都是「ZRIY」，換言之對這兩個變形部首都是取「IY」。
這不合理吧？
漢字區的「氵」本身取「YM」，是合理的。所以變形部首應取「ZRYM」。
漢字區的「辶」拆「INNO」，用的是台標字形。應增加傳承字形的取碼「YNO」。而傳承字形的變形部首應取「ZRYNO」。

**Comment by Jackchows** [comment]
已修改。
