### ISSUE TITLE
「𢷖」

### ISSUE THREAD

**Issue by SyaoranHinata** [Jackchows/Cangjie5#74]
「𢷖」目前取「手女戈戈」和「難手女戈戈」
應取「手女女戈」

**Comment by SyaoranHinata** [comment]
「𩪽」目前取「月月心戈中」
如果「斷、繼」等字仍取「女」，似乎不宜只有「𩪽」字脫隊取「心」。
要麼全部「㡭」部件都兼容取「心女戈戈」的拆法，要麼「𩪽」字取「月月女戈中」。

**Comment by Jackchows** [comment]
已修改。
