### ISSUE TITLE
「叉、戏」改序失效了？

### ISSUE THREAD

**Issue by SyaoranHinata** [Jackchows/Cangjie5#79]
記得以前提報過應「先叉後戏」，然後改好了的。
但剛剛盲打文章，出帖後才發現「叉燒、叉字」等詞全都錯成「戏」字。是否失效了？@_@

**Comment by Jackchows** [comment]
因為後來新增了傳統漢字優先版本，重新考慮之後，一般排序版本在**commit** [**90ef3c2**](https://github.com/Jackchows/Cangjie5/commit/90ef3c23dada7fb445f540a1afd71765b193f71a)中修改回原來的排序「戏叉」。

**Comment by SyaoranHinata** [comment]
……但「叉」字也太常用了吧…
竊以爲，若正（繁）體和簡體都屬常用字，仍應以正體爲先。

**Comment by SyaoranHinata** [comment]
朱先生他自己也是這麼說的：「若重碼者，依先繁後簡的次序。」
要是簡體是常用字，正體不是常用字，那麼先排簡體也無不可。
但若正簡都屬常用字，那麼先簡後正，竊以爲有違官方原意之餘也不合理。

**Comment by Jackchows** [comment]
傳統漢字優先版本已經實現了「若重碼者，依先繁後簡的次序」，一般排序版本還這樣排的話，兩個版本又有甚麼不同呢？

**Comment by Jackchows** [comment]
傳統漢字優先版本「戏叉」排序出錯了，稍後將修正。

**Comment by SyaoranHinata** [comment]
明白，謝謝。

以我理解，傳統漢字優先版本就是必定傳統漢字優先；簡化字優先就是必定簡化字優先；一般排序版本會綜合考慮字頻及繁簡：若繁體罕用簡體常用，這時候簡體優先，但若繁簡皆常用，仍是繁體優先。這是三者的分別。
