### ISSUE TITLE
對倉頡編碼補完計畫的一些想法

### ISSUE THREAD

**Issue by danny0838** [Jackchows/Cangjie5#83]
既然都要花時間整理，為增加成果的實用性，我覺得補完計畫最好能使用可直接製成輸入法使用的格式（例如 RIME 方案格式）、各代倉頡併行、同時提供整理過的官方編碼表和我們修訂的編碼表、把不同功能的編碼表分開成不同檔案（漢字、重碼字、特殊符號、康熙部首、中日韓相容表意字元等）。細節寫在[三代補完計畫](https://github.com/Arthurmcarthur/Cangjie3-Plus/issues/12#issuecomment-401582734)。不曉得各位有什麼想法？

基於這些目的我開了一個[整合專案](https://github.com/danny0838/rime-cangjie-integrated)，之後會逐步合併 RIME 官方編碼表、補完計畫的編碼表、以及六代倉頡的編碼表等等。各位如有興趣也歡迎加入。

**Comment by mrhso** [comment]
Rime 所使用的词典没有固定格式。

**Comment by danny0838** [comment]
RIME 要求詞典檔前半部符合 YAML，後面是符合 YAML 定義欄位的 TSV，否則就是格式錯誤。你說沒有固定格式是指什麼？

**Comment by mrhso** [comment]
columns 的顺序可以自己调整（不过一般来说还是先 text 再 code 比较好）

**Comment by danny0838** [comment]
這點專案自已統一就好，甚至不統一也不影響使用，有什麼影響嗎？

**Comment by SyaoranHinata** [comment]
其實這個我也有點意見，坊間所見，很大部份碼表都是先放字碼，後放字元的，即是「etlo 漢」。
包括「倉頡之友．馬來西亞」的碼表，或者本計劃的相關項目 [Arthurmcarthur/Cangjie3-Plus](https://github.com/Arthurmcarthur/Cangjie3-Plus) 都是這樣。
但這裏的碼表卻是「漢 etlo」。
雖然不是甚麼重點，但感覺統一作先放字碼，後放字元，會跟各方一致得多。

**Comment by mrhso** [comment]
但是在 Rime 没写 columns 的话，默认应该是先放字再放码。

**Comment by danny0838** [comment]
先放字或先放碼主要是由平台支援決定，如果都可以，那就視實際需求而定。

對我來說，由於我要讓編碼表按編碼排序，所以會偏好把編碼放在前面。同理，如果打算按字元（的 Unicode 順序）排序，把字放前面會方便些。

**Comment by Jackchows** [comment]
個人覺得將字放前面看起來整齊些。
