### ISSUE TITLE
有關「𣎆」和「𦝠」

### ISSUE THREAD

**Issue by SyaoranHinata** [Jackchows/Cangjie5#84]
按Unicode預設字形，「𣎆」末碼爲「弓」，「𦝠」末碼爲「大」。
現在的碼表，打「卜弓」或「卜大」，皆先「𣎆」後「𦝠」；打「卜女口月弓」或「卜女口月大」亦皆先「𣎆」後「𦝠」。
這樣並不符合字形，亦對「𦝠」字不公。

建議修改作：
1. 打「卜弓」、「卜女口月弓」只有「𣎆」，打「卜大」、「卜女口月大」只有「𦝠」； 或
2. 打「卜弓」、「卜女口月弓」先「𣎆」後「𦝠」；打「卜大」、「卜女口月大」先「𦝠」後「𣎆」。

**Comment by Jackchows** [comment]
同意修改。

**Comment by danny0838** [comment]
`change_summary.md` 有提到「若同一字的不同字形在 Unicode 中分開編碼，亦不設字形兼容。」

按此原則，既然 Unicode 已經把「𣎆」「𦝠」分開，兩者的輸入碼是否應該不互相兼容？（即頂樓的方案 1：「卜弓」、「卜女口月弓」只有「𣎆」，打「卜大」、「卜女口月大」只有「𦝠」）

**Comment by danny0838** [comment]
瞭解
