### ISSUE TITLE
「𦥑」

### ISSUE THREAD

**Issue by SyaoranHinata** [Jackchows/Cangjie5#86]
要是依倉頡規則，「𦥑」和「臼」都是難字，取「竹難」。
難字與複合字一樣，與複合字首不同，無論作字首、字身還是獨用，理論上都取難字。
但「𦥑」[於《漢文》取「竹心尸一」](http://www.hanculture.com/dic/list.php)，似有不符。

那麼，依規則而言，「𦥑」獨用時是否也應取「竹難」呢？
（個人以爲「竹心尸一」也宜同時保留，兼容二者。）

**Comment by Jackchows** [comment]
同意保留兩者。
