### ISSUE TITLE
「𢎘」

### ISSUE THREAD

**Issue by SyaoranHinata** [Jackchows/Cangjie5#88]
「𢎘」目前只取「尸女尸」，不取「弓女尸」。「𠮤、𡴰、𢪜、𤜛」亦然。但其實「弓女尸」的字形挺常見的。建議支援「弓女尸」的取法。

而「㽕、𢎙、𣎺」從「𢎘」，但目前「𢎘」部份只取「弓女尸」，不取「尸女尸」。

「𩎩」更拆「木手木月尸」，怪異哉。

按：新版五代把它增加作「尸」輔根，可考慮從之。

**Comment by Jackchows** [comment]
「𠮤、𡴰、𢪜、𤜛」作「弓女尸」的字形有沒有出處？

**Comment by SyaoranHinata** [comment]
從「𢎘」類推的。
