### ISSUE TITLE
Unicode 字形相關標示是根據哪裡的資料定義？

### ISSUE THREAD

**Issue by danny0838** [Jackchows/Cangjie5#89]
目前表中的 `[u] Unicode文檔未列出字形` 和 `[U] UCS2003字形` 具體是根據哪裡的資料定義？能否附上相關連結呢？

舉例來說，目前表中有：

    paiu	𠣹
    phpu	𠣹
    phsu	𠣹	[u]

但[實際查 Unihan 資料庫](https://www.unicode.org/cgi-bin/GetUnihanData.pl?codepoint=%F0%A0%A3%B9)，圖片顯示的字形是 `paiu`，如果是按照該圖片，`phpu` 和 `phsu` 都要標上 `[u]` 才對。如果查該資料庫附錄的 GlyphWiki，則列出的是 `phsu` 的字形。這些看起來都不太符合目前的標示……。

**Comment by mrhso** [comment]
首先这个定义要什么资料？本来就是自定义符号，表达那个意思就可以了。
其次 UCS2k3 是历史遗留问题，我们其实已经废弃了这个源。
因为当初 ISO/IEC 10646 的扩展 B 没有列出各提交源的参考字形，而是单一的参考字形，字体由中易制作。
后来单列扩多列的时候就把原来中易所制作的这个字体作为 UCS2k3 放入了。但是这个字形有各种各样的错误，有的是提交源后来更改，有的是中易造错了，……

**Comment by danny0838** [comment]
所以目前是以 Code Chart 為依據？

那麼按照 [Unicode Ext-B 的 Code Charts](https://unicode.org/charts/PDF/U20000.pdf):
![default](https://user-images.githubusercontent.com/531417/42416301-88e805d4-829d-11e8-834a-4a658967c126.png)

應該把頂樓的字改成：

    paiu	𠣹
    phpu	𠣹	[u]
    phsu	𠣹	[u]

是嚜？

**Comment by Jackchows** [comment]
phpu 確實是漏標了。

**Comment by danny0838** [comment]
除了 Code Charts 以外，Unicode 也建立了一套異體字形標準在 [Ideographic Variation Database (IVD)](https://unicode.org/ivd/)，裡面有定義漢字的異體字形。

例如「冗」（U+5197）在 Unicode Code Charts 只有「月竹弓」一種字形：

![default](https://user-images.githubusercontent.com/531417/42420929-d99da04e-82ff-11e8-9793-d953e50b79a3.png)

但查 [IVD 資料庫 2017-12-12 版資料](https://unicode.org/ivd/data/2017-12-12/)，就會發現有定義 5197 E0102 是「月竹山」的字形：

![default](https://user-images.githubusercontent.com/531417/42420983-962a2d22-8300-11e8-8591-0a0e0fd2fc1f.png)

![default](https://user-images.githubusercontent.com/531417/42420979-91493046-8300-11e8-90f4-26a8bc39ed42.png)

按此，`冗	bhu	[ou]` 應去掉 `[u]` 標記。

**Comment by Jackchows** [comment]
因為精力有限，目前第一遍檢查基本都沒有查IVD。
可以加個IVD標記。

**Comment by danny0838** [comment]
Unicode 標準就是 Unicode 標準，我傾向不區分 Unicode Code Charts 和 IVD，兩者都沒有才標 [u]。

**Comment by Jackchows** [comment]
因為在做字形兼容的時候，發現有一些字，Code Charts 衹收了一種字形。這時候需要考慮要不要類推出另一種字形：如果不類推，用起來可能不方便。如果類推，又不知道以後 UCS 會不會給這個字形單獨編碼。所以就折衷標個 [u] ，這是最初標 [u] 的目的。
把 Code Charts 和 IVD 分開標註的好處是，如果有人不想用 IVD，篩選起來比較方便。

**Comment by danny0838** [comment]
這樣說似乎也是，但似乎更像是為了「想用 IVD」的人使用（輸入編碼得出對應的 code + VS）。而且這麼一來便不是 IVD 未編的要標示，而是 IVD 有定義的都要標示了？

您建議用什麼符號？如果要標，是否也要標示 IVD 的 ID？

**Comment by Jackchows** [comment]
我想這樣：
用 [u] 標記 Code Charts 未收的字形。
用 [uv] 標記 Code Charts 未收而 IVD  有收的字形。
暫時不打算標示 IVD 的 ID。

**Comment by danny0838** [comment]
Code Charts 和 IVD 都有收的字形要怎麼做？不標記？標 [v]？

**Comment by Jackchows** [comment]
因為目前階段我不會每個字都去查IVD，所以我覺得一個字母表示單一變量比較方便。
[u] 對應 Code Charts 有沒有收，[v] 對應 IVD 有沒有收。
Code Charts 和 IVD 都有收的字形不需標記。

**Comment by Jackchows** [comment]
IVD 有收的字形雖然不會另外單獨編碼，但仍可能統合（unify）到現有漢字（即在 Code Charts 增加字形），因此標 [u] 合理。

**Comment by danny0838** [comment]
@Jackchows:

我不贊成這個方案，我認為它非常不方便：

第一，我們編碼時只需要關注一個字是否「未來可能被編到另一個 Unicode 碼位」，並沒有需要去區分「在 Code Charts」的字和「不在 Code Charts 但在 IVD」的字。做這種區分反而導致我們需要去篩選「沒有標上 [u] 的字以及有標上 [uv] 的字」才能判斷一個字是否「未來可能被編到另一個 Unicode 碼位」，徒增困擾。

第二，按你的方案，只有「IVD 有收」且「Unicode Code Charts 沒收」可以標上 [v]，這就讓 [v] 代表了兩個變量而不是單一變量，並沒有讓邏輯更簡單。

第三，按你的方案，[u] 是「Unicode Code Charts **沒有**收」的字，[v] 是「IVD **有**收」的字，這種邏輯不一致也會讓實際標示時容易混淆而出錯。

我認為我們基本上沒有必要關注一個字是否有被 IVD 定義（除非像之前提到的，要讓未來支援「輸入倉頡碼得到對應 code + VS」，但要這麼做就得把所有 IVD 定義的字都標上記號且記明異體編號，且即便如此倉頡編碼也未必能有效區分所有 IVD 異體。總之這實在太煩瑣了，我認為現階段根本不需要考慮）。

因此，我會選擇稍微調整 [u] 標記的定義為 `Unicode 尚未承認的字`＝`未來有可能被 Unicode 編碼至另一碼位的字`，目前其操作型定義為 `Unicode Code Charts 未收且 IVD 未收的字`；若未來 Unicode 有其他類似 IVD 的異體字處理方案，也可以納入此定義。

這樣便不需要對既有系統做太大變動：(1) 文檔改幾個字；(2) 有空去 IVD 查一下標上 [u] 的字，如果 IVD 已有定義就拿掉 [u] 標記。（實際上擴展區的字很少會被收入 IVD，初步可以只查基本區的字，未來遇到再慢慢改就好）

**Comment by Jackchows** [comment]
我希望區分某個字形是在 Code Charts 收錄還是在 IVD 收錄。不過僅在 Code Charts 沒收的情況下，才需要考慮 IVD 有沒有收。
或者可以這樣：
[u] 表示 Code Charts 未收錄
[U] 表示 Code Charts 收錄（特指 UCS2003 字形，因為普通情況不必標記）
[v] 表示 IVD 未收錄
[V] 表示 IVD 收錄
這樣的話，有四種情況：
1. Code Charts有收，IVD有收→不標記
2. Code Charts有收，IVD沒收→不標記
3. Code Charts沒收，IVD有收→uV
4. Code Charts沒收，IVD沒收→uv

**Comment by danny0838** [comment]
這樣至少比較合理，在有更好的方案出來之前，我暫時接受這麼做。
