### ISSUE TITLE
「𢧠」

### ISSUE THREAD

**Issue by danny0838** [Jackchows/Cangjie5#92]
此字目前編碼為「vbi」，Unicode Code Charts 有數個字形：

![default](https://user-images.githubusercontent.com/531417/42421147-65772aa6-8303-11e8-9cbb-5643b0fc0adf.png)

若按前兩個字形，似乎應編作「女戈.月」；若按第三個字形，似乎應編作「日月.戈」。

**Comment by SyaoranHinata** [comment]
其實有時碰到「⿺𠃊日」或「⿺𠃊目」之形，
會有應該先取「女」還是先取「日/目」之爭。

**Comment by Jackchows** [comment]
前兩個字形不能取「女」，我覺得應該取「中戈月」。後面一個字形可斟酌一下先取「女」還是先取「日」。

**Comment by danny0838** [comment]
「⿺𠃊日」形「女」包覆了「日」的兩面，如果按「由外而内」原則一律先取女，會不會有其他爭議？
