### ISSUE TITLE
「𠘀」

### ISSUE THREAD

**Issue by danny0838** [Jackchows/Cangjie5#94]
「𠘀」目前編碼為「alry」「airy」「arkim」，有點不明所以。

這個字也有多種異體：

![default](https://user-images.githubusercontent.com/531417/42421625-3affca82-830b-11e8-98ba-53735ca201d0.png)

按 UCS2003 字形，中豎看作連接，「大」一般視作與上相連、不與下相連（如：貵＝戈大.月山金），故應取碼「日大.戈一」。後面兩個字形，「丶」一般不視作與上下相連，故應取碼「日.戈.口卜」。

末兩筆「卜」和「戈一」或可考慮互相兼容。

**Comment by Jackchows** [comment]
官方資料並未提及「『大』一般視作與上相連」，「参」、「貵」等字的取碼本來就有爭議。「篡」、「罨」等字也是反例。
U源字形可取「日口.大.戈一」，G源取「日.戈.口卜」，T源中間看起來是一短竪，似乎可以取「日.中日.卜」。
這個字 UCS2003 字形有明顯差異，如果這個字形沒有其他來源，我認為可以不收。

**Comment by SyaoranHinata** [comment]
同意「卜」和「戈一」互相兼容。像「冬、寒、冭」等部件會相關。
