### ISSUE TITLE
「𣤞」「𬅮」「𩔰」

### ISSUE THREAD

**Issue by danny0838** [Jackchows/Cangjie5#95]
目前編碼：𣤞（amno）、𬅮（acno）、𩔰（acmbc）

「並」拆作「廿廿金」，「亚」拆作「一廿金」，作字首末碼時應按「包含省略」原則取「金」。

故三字應編碼為：𣤞（atno）、𬅮（atno）、𩔰（atmbc）

**Comment by SyaoranHinata** [comment]
無論三代或五代，「並」部件並不適合套用「包含省略原則」。例如「譜」是取「卜口.廿金.日」而不是「卜口.廿廿日」。「亚」部件應同理。

而且，五代手冊已說明「工、土、王」等鑲嵌形空框並不適合套用「包含省略原則」。而「並、亚」的「Ⅱ」也是鑲嵌形空框，因此在五代中，也肯定不適合套用「包含省略原則」。

故三字應編碼爲：𣤞（日金弓人acno）、𬅮（日金弓人acno）、𩔰（日金一月金acmbc）

**Comment by SyaoranHinata** [comment]
至於𣤞（日一弓人amno），可視爲對右下方「並」字兩種寫法的兼容碼，不必刪去，但宜補上𣤞（日金弓人acno）。

**Comment by danny0838** [comment]
對，不能包含省略，是我弄錯了。

不過「𣤞」字我不傾向設兼容碼。

**Comment by SyaoranHinata** [comment]
![image](http://glyphwiki.org/glyph/u4e26@3.50px.png)、![image](http://glyphwiki.org/glyph/u4e26-07-var-001@1.50px.png)
