### ISSUE TITLE
「㞊」有兩種字形

### ISSUE THREAD

**Issue by danny0838** [Jackchows/Cangjie5#96]
之前把「㞊」的 UFKU 改成 UFIKU，但其實 Unicode 有收兩個字形：

![default](https://user-images.githubusercontent.com/531417/42461005-0cc2a3c0-83d2-11e8-9a90-c7e7c63c3aac.png)

應該做兼容處理。

**Comment by SyaoranHinata** [comment]
>之前把「㞊」的 **U**FKU 改成 **U**FIKU
