### ISSUE TITLE
「尷」類字形是否要兼容「尢／九」？

### ISSUE THREAD

**Issue by danny0838** [Jackchows/Cangjie5#97]
如題，「尷」類字的左邊 Unicode 往往有收「尢」和一個類似「九」的形狀：

![default](https://user-images.githubusercontent.com/531417/42461679-a663c846-83d3-11e8-9505-2666c041e930.png)

但不曉得是否為 Unicode 字體問題，圖中的「九」似乎有突出頭，和真正作為偏旁的「九」不太一樣，例如和左邊確實是「九」的「旭」字對照：

![default](https://user-images.githubusercontent.com/531417/42461951-6f87af26-83d4-11e8-9296-9d74919801a9.png)

不過個別幾個字確實有「九」的異體，且字典把計算為 2 劃：

![default](https://user-images.githubusercontent.com/531417/42462203-26e58daa-83d5-11e8-94d9-7f6c308cedb7.png)

有些倉頡會設「大弓＊」的編碼。

我們要兼容兩種取法嗎？

**Comment by SyaoranHinata** [comment]
尬/𠆷，拋/抛 ←Unicode是分別編碼的

**Comment by danny0838** [comment]
瞭解，看樣子是不用設兼容。
