### ISSUE TITLE
「感」類字應兼容「戈口心／戈竹一口心」

### ISSUE THREAD

**Issue by danny0838** [Jackchows/Cangjie5#99]
如題，Unicode 「感」有收兩字形：

![default](https://user-images.githubusercontent.com/531417/42464484-c642ce52-83db-11e8-8915-376fe65e0c05.png)

G源取「戈口.心」，T源取「戈竹.一.口心」。

衍生字同理。

**Comment by Jackchows** [comment]
官方沒有兼容此字形，暫時不考慮添加。
